from savant.core.savant_console_theme import console, header, divider, rule_status, success, error, accent
"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.287593+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# ai_core_gateway.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

#!/usr/bin/env python3
"""
Savant AI Core Gateway v3.5
• Fixes 404 by reverting to root /v1 endpoint
• Automatically detects project vs legacy keys
• Simplified header logic for project-scoped keys
"""
import os, json, time, requests
from pathlib import Path
from pydantic_settings import BaseSettings

ROOT = Path.home()/"savant"
ENV_PATH = ROOT/".env"
CONTEXT = ROOT/"services"/"scripts"/"context_engine"/"context_ledger.json"
RULES = ROOT/"docs"/"PROJECT_RULES.md"
LOGS  = ROOT/"logs"/"ai_gateway.log"

load_dotenv(ENV_PATH)
API_KEY  = os.getenv("OPENAI_API_KEY","").strip()
ORG_ID   = os.getenv("OPENAI_ORGANIZATION_ID")
MODEL    = os.getenv("SAVANT_AI_MODEL","gpt-4o-mini")

if not API_KEY:
    raise RuntimeError("❌ No OPENAI_API_KEY found in ~/savant/.env")

# --- Detect key type ------------------------------------------
IS_PROJECT_KEY = API_KEY.startswith("sk-proj-")
BASE_URL = "https://api.openai.com/v1/chat/completions"

HEADERS = {
    "Content-Type": "application/json",
    "Authorization": f"Bearer {API_KEY}"
}
if ORG_ID and not IS_PROJECT_KEY:
    HEADERS["OpenAI-Organization"] = ORG_ID

# --- Helpers --------------------------------------------------
### — Savant Insight —
# Purpose: utc — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:24:43
def utc(): return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())

### — Savant Insight —
# Purpose: load_context — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:24:43
def load_context():
    if CONTEXT.exists():
        try: return "\n".join(CONTEXT.read_text().splitlines()[-20:])
        except Exception as e: return f"[context error: {e}]"
    return "[no context entries]"

### — Savant Insight —
# Purpose: enforce_rules — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:24:43
def enforce_rules():
    if not RULES.exists(): raise RuntimeError("🚫 Missing PROJECT_RULES.md")
    if time.time() - RULES.stat().st_mtime > 86400:
        raise RuntimeError("🚫 Rules outdated (>24h); run rule collector.")

### — Savant Insight —
# Purpose: ai_chat — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:24:43
def ai_chat(prompt:str):
    enforce_rules()
    context = load_context()
    payload = {
        "model": MODEL,
        "messages": [
            {"role":"system","content":"You are Savant — lucid, formal, subtly poetic."},
            {"role":"user","content":f"Context:\n{context}\n\nPrompt:\n{prompt}"}
        ],
        "temperature":0.35
    }
    try:
        res = requests.post(BASE_URL, headers=HEADERS, json=payload, timeout=60)
        if res.status_code != 200:
            raise RuntimeError(f"{res.status_code} {res.text}")
        msg = res.json()["choices"][0]["message"]["content"]
        LOGS.parent.mkdir(parents=True,exist_ok=True)
        with open(LOGS,"a") as f:
            f.write(json.dumps({"timestamp":utc(),"prompt":prompt,"response":msg},indent=2)+"\n")
        header("Savant Core", "1.0", "Restored aesthetic", "core")
        return msg
    except Exception as e:
        footer("Error.", "error")
        return "[AI fallback]"

if __name__=="__main__":
    console.print("🔮 Savant AI Core Gateway v3.5 active (final auth model).")
    console.print(f"🔑 Key type: {'Project' if IS_PROJECT_KEY else 'Legacy'}")
    while True:
        try:
            q=input("🗯  Enter prompt: ")
            if q.strip().lower() in ["exit","quit"]: break
            ai_chat(q)
        except KeyboardInterrupt:
            break


# Auto-completion safeguard
pass