from savant.core.savant_console_theme import console, header, divider, rule_status, success, error, accent
"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.285433+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# ai_core.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

#!/usr/bin/env python3
"""
SAVANT AI CORE v2.2
• Centralized gateway for all intelligent operations.
• Enforces PROJECT_RULES.md before every completion.
• Writes reference numbers to context ledger.
• Provides unified interface to OpenAI-compatible models.
"""

import os, sys, json, uuid, time, subprocess
from pathlib import Path
from datetime import datetime, timezone
from pydantic_settings import BaseSettings
from openai import OpenAI

ROOT = Path.home() / "savant"
DOCS = ROOT / "docs"
LOGS = ROOT / "logs"
LEDGER = ROOT / "services" / "scripts" / "context_engine" / "context_ledger.py"
ENFORCER = ROOT / "services" / "scripts" / "rule_engine" / "enforcer.py"

### — Savant Insight —
# Purpose: utc — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:21:50
def utc(): return datetime.now(timezone.utc).isoformat()
### — Savant Insight —
# Purpose: ref — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:21:50
def ref(tag="post"): return f"{int(time.time()*1000)}-{uuid.uuid4().hex[:6]}-{tag}"

# --- Rule enforcement -------------------------------------------
### — Savant Insight —
# Purpose: check_rules — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:21:50
def check_rules():
    try:
        subprocess.run([sys.executable, str(ENFORCER)], check=True, capture_output=True)
    except subprocess.CalledProcessError as e:
        console.print("❌ Rule enforcement failed:\n", e.stderr.decode())
# 🔸 BEGIN_SNIPPET snippet_0 [2b9e6acbd2]
<span style='color:#c7a740'>#!/usr/bin/env python3
"""
Post-completion enhancement engine.
"""</span>
# 🔸 END_SNIPPET
        sys.exit(1)

# --- Ledger logging ---------------------------------------------
### — Savant Insight —
# Purpose: log_to_ledger — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:21:50
def log_to_ledger(entry:dict):
    LEDGER.parent.mkdir(parents=True, exist_ok=True)
    with open(ROOT/"logs"/"context_ledger.log","a") as f:
        f.write(json.dumps(entry)+"\n")

# --- OpenAI gateway ---------------------------------------------
### — Savant Insight —
# Purpose: get_client — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:21:50
def get_client():
    load_dotenv(Path.home() / "savant" / ".env")
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        raise EnvironmentError("OPENAI_API_KEY missing from .env")
    return OpenAI(api_key=api_key)

### — Savant Insight —
# Purpose: ai_chat — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:21:50
def ai_chat(prompt:str, model="gpt-4o-mini"):
    check_rules()
    client = get_client()
    ref_id = ref("chat")
    log_to_ledger({"ref":ref_id,"timestamp":utc(),"type":"chat","prompt":prompt})
    try:
        res = client.chat.completions.create(
            model=model,
            messages=[{"role":"system","content":"You are Savant — speak with lucid precision and subtle poetry."},
                      {"role":"user","content":prompt}],
            temperature=0.7
        )
        reply = res.choices[0].message.content.strip()
        log_to_ledger({"ref":ref_id,"timestamp":utc(),"type":"reply","content":reply})
        header("Savant Core", "1.0", "Restored aesthetic", "core")
    except Exception as e:
        log_to_ledger({"ref":ref_id,"timestamp":utc(),"error":str(e)})
        footer("Error.", "error")

if __name__=="__main__":
    prompt = " ".join(sys.argv[1:]) if len(sys.argv)>1 else input("Enter prompt: ")
    ai_chat(prompt)

# Auto-completion safeguard
pass