"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.286288+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# ai_gateway.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

"""
Enhanced by Savant Clean+Complete Cluster v1.0 — 2025-10-30T06:11:07.462073+00:00
"""
#!/usr/bin/env python3
from fastapi import FastAPI, Form, Request
from fastapi.responses import HTMLResponse
from pydantic import BaseModel
from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[3]))
from services.scripts.ai_core.ai_core import ai_chat

app = FastAPI(title="Savant AI Gateway", version="2.1")

### — Savant Insight —
# Purpose: PromptRequest — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:23:05
class PromptRequest(BaseModel):
    prompt: str

@app.post("/chat")
async def chat(req: PromptRequest):
    try:
        reply = ai_chat(req.prompt, model="gpt-4o")
        return {"status":"ok","reply":reply}
    except Exception as e:
        return {"status":"error","message":str(e)}

@app.get("/chat-form", response_class=HTMLResponse)
async def chat_form():
    return """
    <html><body style="background:#111;color:#e4c66f;font-family:JetBrains Mono;">
    <h2>Savant AI Gateway</h2>
    <form action="/chat-form" method="post">
      <textarea name="prompt" rows="4" cols="60" style="background:#1e1e21;color:#e4c66f;border:1px solid #c7a740;"></textarea><br>
      <input type="submit" value="Send" style="background:#2e2e32;color:#c7a740;padding:6px 12px;">
    </form></body></html>
    """

@app.post("/chat-form", response_class=HTMLResponse)
async def chat_form_post(prompt: str = Form(...)):
    try:
        reply = ai_chat(prompt, model="gpt-4o")
        return f"<pre style='background:#1e1e21;color:#e4c66f;padding:1em;'>{reply}</pre>"
    except Exception as e:
        return f"<pre style='color:red;'>Error: {e}</pre>"

@app.get("/status")
async def status():
    return {"status":"running","engine":"Savant AI Core 2.1"}

if __name__=="__main__":
    import uvicorn
    uvicorn.run("services.scripts.ai_core.ai_gateway:app", host="0.0.0.0", port=8080)


# Auto-completion safeguard
pass