from savant.core.savant_console_theme import console, header, divider, rule_status, success, error, accent
"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.306432+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# governor.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

#!/usr/bin/env python3
"""
SAVANT GOVERNOR v9.1
Unified controller for Deep Research, Enhancement, and Personality engines.
Termux-stable import resolver included.
"""

import os
import sys
import json
from datetime import datetime, timezone

# --- Universal Path Injection ----------------------------------
# Guarantee ~/savant is importable no matter where this runs
BASE_PATH = os.path.expanduser("~/savant")
SCRIPT_PATH = os.path.join(BASE_PATH, "services", "scripts")
if BASE_PATH not in sys.path:
    sys.path.append(BASE_PATH)
if SCRIPT_PATH not in sys.path:
    sys.path.append(SCRIPT_PATH)

# --- Dynamic Import Recovery -----------------------------------
try:
    from savant.services.scripts.personality_engine.deep_research.research_core import DeepResearchEngine
    from savant.services.scripts.personality_engine.enhancement_engine.enhancement_core import EnhancementEngine
    from savant.services.scripts.personality_engine.governor_core.governor_bridge_hook import run_bridge
    from savant.services.event_bus.event_bus_core import publish
except ModuleNotFoundError as e:
    console.print(f"⚠ Import error: {e}")
    console.print("🔧 Attempting self-healing import patch...")
    sys.path.extend([
        os.path.join(BASE_PATH, "services"),
        os.path.join(BASE_PATH, "services", "scripts", "personality_engine"),
    ])
    from savant.services.scripts.personality_engine.deep_research.research_core import DeepResearchEngine
    from savant.services.scripts.personality_engine.enhancement_engine.enhancement_core import EnhancementEngine
    from savant.services.scripts.personality_engine.governor_core.governor_bridge_hook import run_bridge
    from savant.services.event_bus.event_bus_core import publish


# --- Governor Definition ---------------------------------------
### — Savant Insight —
# Purpose: SavantGovernor — auto-annotated by Savant DocSynth
# Added 2025-10-30 20:02:08
class SavantGovernor:
    """
    Oversees research, enhancement, and personality-driven cycles.
    Handles reflection, reporting, and context synchronization.
    """

    def __init__(self):
        self.research_engine = DeepResearchEngine()
        self.enhancement_engine = EnhancementEngine()
        self.bridge = run_bridge()

        publish("governor_init", {
            "status": "initialized",
            "timestamp": datetime.now(timezone.utc).isoformat()
        })

    # --- Core Cycle ---------------------------------------------
    def run_cycle(self):
        console.print("\n=== SAVANT GOVERNOR CORE ===")
        console.print("Choose Mode:")
        console.print("1. Deep Research")
        console.print("2. Enhancement")
        mode = input("> ").strip()

        if mode == "1":
            topic = input("Enter research topic: ").strip()
            console.print(f"🔍 Researching '{topic}'...")
            try:
                report_path, word_count = self.research_engine.conduct_research(topic)
                publish("research_cycle_complete", {
                    "topic": topic,
                    "words": word_count,
                    "path": report_path,
                    "timestamp": datetime.now(timezone.utc).isoformat()
                })
                footer("Complete.", "done")
            except Exception as e:
                publish("research_cycle_error", {"topic": topic, "error": str(e)})
                rule_status(f"❌ Research failed: {e}", "error")

        elif mode == "2":
            target = input("Enter file or directory to enhance: ").strip()
            console.print(f"⚙ Enhancing {target}...")
            try:
                modified = self.enhancement_engine.enhance(target)
                publish("enhancement_cycle_complete", {
                    "target": target,
                    "modified": modified,
                    "timestamp": datetime.now(timezone.utc).isoformat()
                })
                footer("Complete.", "done")
            except Exception as e:
                publish("enhancement_cycle_error", {"target": target, "error": str(e)})
                rule_status(f"❌ Enhancement failed: {e}", "error")

        else:
            publish("governor_invalid_selection", {
                "selection": mode,
                "timestamp": datetime.now(timezone.utc).isoformat()
            })
            console.print("⚠ Invalid selection.")


# --- Execute ----------------------------------------------------
if __name__ == "__main__":
    governor = SavantGovernor()
    governor.run_cycle()


# Auto-completion safeguard
pass