"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.289931+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# comment_injector.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

#!/usr/bin/env python3
"""
Comment Injector — Savant Style Standardizer
--------------------------------------------
Applies Savant documentation format:
  ◦ clear technical docstrings
  ◦ purpose, behavior, and error semantics
  ◦ subtle poetic cadence without obscuring clarity
"""
import os
from pathlib import Path
TEMPLATE = """# ===============================================================
# {name}
# Purpose:
#   {desc}
#
# Behavior:
#   {behavior}
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================
"""
ROOT = Path.home() / "savant"
for p in (ROOT/"services").rglob("*.py"):
    txt = p.read_text(encoding="utf-8", errors="ignore")
    if not txt.strip().startswith("# ==============================================================="):
        header = TEMPLATE.format(name=p.name, desc="Autogenerated summary.", behavior="Core function of Savant module.")
        p.write_text(header + "\n" + txt, encoding="utf-8")
footer("Complete.", "done")

# Auto-completion safeguard
pass
