"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.289593+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# immutable_guard.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

#!/usr/bin/env python3
"""
Immutable Guard — Savant Core Enforcement Layer
------------------------------------------------
Prevents silent overwrites by:
  • Hashing each script on save
  • Storing backup before write
  • Appending rather than replacing existing content
  • Embedding version metadata header

Every modification is logged in ~/savant/logs/guard_activity.log
"""
import hashlib, os, shutil
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path.home() / "savant"
LOG = ROOT / "logs" / "guard_activity.log"
### — Savant Insight —
# Purpose: log — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:27:46
def log(msg:str):
    LOG.parent.mkdir(parents=True, exist_ok=True)
    LOG.write_text(f"[{datetime.now(timezone.utc).isoformat()}] {msg}\n", append=True if LOG.exists() else False)

### — Savant Insight —
# Purpose: hash_file — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:27:46
def hash_file(path:Path)->str:
    h=hashlib.sha256()
    with open(path,"rb") as f:
        for chunk in iter(lambda: f.read(8192),b""): h.update(chunk)
    return h.hexdigest()

### — Savant Insight —
# Purpose: protect — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:27:46
def protect(path:Path):
    if not path.exists(): return
    h=hash_file(path)
    ts=datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    backup=path.with_suffix(path.suffix+f".bak_{ts}")
    shutil.copy2(path,backup)
    log(f"Backup created for {path} → {backup} [SHA={h[:8]}]")

if __name__=="__main__":
    for p in (ROOT/"services").rglob("*.py"): protect(p)
    footer("Complete.", "done")

# Auto-completion safeguard
pass
