"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.770118+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# cleanup_engine.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

#!/usr/bin/env python3
"""
SAVANT CLEANUP ENGINE v2.2
Adds:
- Immutable ledger protection
- Interactive visual HTML report
- Intelligent cleanup verification
"""

import os, re, json, shutil, hashlib
from pathlib import Path
from datetime import datetime

BASE = Path.home() / "savant"
LOGS = BASE / "logs"
LEDGER = BASE / "context" / "context_ledger.json"
QUAR = BASE / "quarantine"
HTML_REPORT = LOGS / "cleanup_report.html"

SAFE_EXTS = [".tmp", ".bak", ".old", ".log", ".cache"]
PROTECTED_PATHS = ["context/context_ledger.json", "services/scripts", "services/web"]

### — Savant Insight —
# Purpose: log — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:07:54
def log(msg):
    LOGS.mkdir(parents=True, exist_ok=True)
    with open(LOGS / "cleanup_diagnostics.log", "a") as f:
        f.write(f"[{datetime.utcnow().isoformat()}] {msg}\n")
    print(msg)

### — Savant Insight —
# Purpose: is_temp_file — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:07:54
def is_temp_file(path: Path):
    name = path.name.lower()
    if any(name.endswith(ext) for ext in SAFE_EXTS): return True
    if re.search(r"(backup|copy|temp|old|__pycache__)", name): return True
    return False

### — Savant Insight —
# Purpose: is_protected — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:07:54
def is_protected(path: Path):
    return any(p in str(path) for p in PROTECTED_PATHS)

### — Savant Insight —
# Purpose: hash_file — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:07:54
def hash_file(path):
    try:
        h = hashlib.sha256()
        with open(path, "rb") as f:
            while chunk := f.read(8192):
                h.update(chunk)
        return h.hexdigest()
    except Exception:
        return None

### — Savant Insight —
# Purpose: diagnose — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:07:54
def diagnose():
    log("🔍 Running diagnostics...")
    report = {"deleted": [], "quarantined": [], "protected": [], "retained": []}
    seen = {}
    for root, _, files in os.walk(BASE):
        for name in files:
            p = Path(root) / name
            if is_protected(p):
                report["protected"].append(str(p))
                continue
            if is_temp_file(p):
                report["retained"].append(str(p))
                continue
            h = hash_file(p)
            if h and h in seen:
                report["quarantined"].append(str(p))
            else:
                seen[h] = str(p)
                report["retained"].append(str(p))
    return report

### — Savant Insight —
# Purpose: execute — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:07:54
def execute(report):
    QUAR.mkdir(parents=True, exist_ok=True)
    for f in report["retained"]:
        try:
            missing_ok=True(missing_ok=True)
            log(f"🗑️ Deleted → {f}")
        except Exception as e:
            log(f"⚠️ Could not delete {f}: {e}")
    for f in report["quarantined"]:
        try:
            shutil.move(f, QUAR / Path(f).name)
            log(f"🧩 Quarantined duplicate → {f}")
        except Exception as e:
            log(f"⚠️ Could not move {f}: {e}")
    log("✅ Cleanup execution complete.")

### — Savant Insight —
# Purpose: write_html — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:07:54
def write_html(report):
    HTML_REPORT.parent.mkdir(parents=True, exist_ok=True)
    html = [
        "<html><head><meta charset='utf-8'><title>Savant Cleanup Report</title>",
        "<style>body{font-family:Inter;background:#1e1e21;color:#e4c66f;padding:2rem;}h2{color:#f0d98a}ul{margin-bottom:1rem}</style>",
        "</head><body><h1>Savant Cleanup Report</h1>",
        f"<p>Generated: {datetime.utcnow().isoformat()}</p>"
    ]
    for cat, items in report.items():
        html.append(f"<h2>{cat.title()} ({len(items)})</h2><ul>")
        for i in items:
            html.append(f"<li>{i}</li>")
        html.append("</ul>")
    html.append("</body></html>")
    HTML_REPORT.write_text("\n".join(html))
    log(f"📊 HTML report generated → {HTML_REPORT}")

### — Savant Insight —
# Purpose: verify_ledger — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:07:54
def verify_ledger():
    if not LEDGER.exists():
        log("🚨 Context ledger missing! Reconstructing...")
        LEDGER.parent.mkdir(parents=True, exist_ok=True)
        LEDGER.write_text(json.dumps({
            "meta": {"repaired": datetime.utcnow().isoformat()},
            "entries": [{"msg": "Auto-restored by Cleanup Engine v2.2"}]
        }, indent=2))
        log("✅ Ledger restored.")
    else:
        log("🧱 Ledger integrity verified.")
    os.chmod(LEDGER, 0o444)

### — Savant Insight —
# Purpose: main — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:07:54
def main():
    log("🧠 SAVANT CLEANUP ENGINE v2.2 STARTED")
    verify_ledger()
    report = diagnose()
    execute(report)
    write_html(report)
    log("🩺 Cleanup finished — visual report ready.\n")

if __name__ == "__main__":
    main()


# Auto-completion safeguard
pass