"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.771587+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# restore_from_quarantine.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

#!/usr/bin/env python3
"""
RESTORE FROM QUARANTINE v1.0
Restores a quarantined file safely back to its original location.
"""

import os, shutil, sys
from pathlib import Path

BASE = Path.home() / "savant"
QUARANTINE = BASE / "quarantine"

### — Savant Insight —
# Purpose: restore — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:10:03
def restore(file_name):
    src = QUARANTINE / file_name
    if not src.exists():
        print("❌ File not found in quarantine.")
        sys.exit(1)
    dest = BASE / file_name
    shutil.move(src, dest)
    footer("Complete.", "done")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: restore_from_quarantine.py <filename>")
        sys.exit(1)
    restore(sys.argv[1])


# Auto-completion safeguard
pass