"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.772211+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# time_utils.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

from datetime import datetime, timezone
### — Savant Insight —
# Purpose: utc_now_iso — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:10:59
def utc_now_iso():
    """Return current UTC time as ISO8601 string (Python 3.8 – 3.13 safe)."""
    return datetime.now(timezone.utc).isoformat()


# Auto-completion safeguard
pass