from savant.core.savant_console_theme import console, header, divider, rule_status, success, error, accent
"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.281873+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# cloud_sync_daemon.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

#!/usr/bin/env python3
"""
SAVANT CLOUD SYNC DAEMON — v3.5
Uploads archives, exports, and synthesis bundles to S3 automatically.
Reads AWS credentials + bucket from .env or environment.
"""
import os, boto3, time, json, sys
from pathlib import Path
from datetime import datetime
from dotenv import load_dotenv

BASE = Path("~/savant").expanduser()
LOGS = BASE / "logs"
LOGS.mkdir(parents=True, exist_ok=True)
LOG = LOGS / "cloud_sync.log"
load_dotenv(BASE / ".env")

AWS_KEY = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_REGION = os.getenv("AWS_DEFAULT_REGION", "us-east-1")
BUCKET = os.getenv("SAVANT_S3_BUCKET")

### — Savant Insight —
# Purpose: log — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:17:53
def log(msg):
    console.print(msg)
    with open(LOG, "a") as f:
        f.write(f"[{datetime.now().isoformat()}] {msg}\n")

### — Savant Insight —
# Purpose: upload_file — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:17:53
def upload_file(path: Path, prefix="backups/"):
    if not AWS_KEY or not AWS_SECRET or not BUCKET:
        log("⚠️  Missing AWS credentials or bucket in .env")
        return False
    s3 = boto3.client("s3",
        aws_access_key_id=AWS_KEY,
        aws_secret_access_key=AWS_SECRET,
        region_name=AWS_REGION)
    try:
        key = f"{prefix}{path.name}"
        s3.upload_file(str(path), BUCKET, key)
        log(f"✅ Uploaded {path.name} → s3://{BUCKET}/{key}")
        return True
    except Exception as e:
        log(f"❌ Upload failed for {path}: {e}")
        return False

### — Savant Insight —
# Purpose: run_daemon — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:17:53
def run_daemon():
    watch_dir = BASE / "archive"
    watch_dir.mkdir(parents=True, exist_ok=True)
    log(f"🧠 Cloud Sync started — monitoring {watch_dir}")
    while True:
        for f in watch_dir.glob("*.zst"):
            upload_file(f)
        time.sleep(60)

if __name__ == "__main__":
    if len(sys.argv) > 1:
        path = Path(sys.argv[1]).expanduser()
        upload_file(path)
    else:
        run_daemon()

# Auto-completion safeguard
pass
