from savant.core.savant_console_theme import console, header, divider, rule_status, success, error, accent
"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.282471+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# cloud_uplink.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

#!/usr/bin/env python3
"""
SAVANT CLOUD UPLINK v5.1
Uploads Savant archives and backups to S3 safely, with seekable streams.
"""

import os, sys, boto3, time, json
from pathlib import Path
from datetime import datetime
from dotenv import load_dotenv

BASE = Path("~/savant").expanduser()
ARCHIVE = BASE / "archive"
LOGS = BASE / "logs"
LOGS.mkdir(parents=True, exist_ok=True)
LOG_PATH = LOGS / "cloud_uplink.log"
load_dotenv(BASE / ".env")

AWS_KEY = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_REGION = os.getenv("AWS_DEFAULT_REGION", "us-east-1")
BUCKET = os.getenv("SAVANT_S3_BUCKET")

### — Savant Insight —
# Purpose: log — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:18:47
def log(msg: str):
    console.print(msg)
    with open(LOG_PATH, "a") as f:
        f.write(f"[{datetime.now().isoformat()}] {msg}\n")

### — Savant Insight —
# Purpose: upload_file — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:18:47
def upload_file(path: Path, prefix="archive/", retries=3):
    """Upload a single file to S3, using seekable stream"""
    if not path.is_file():
        log(f"⚠️  Skipped non-file: {path}")
        return False
    if not AWS_KEY or not AWS_SECRET or not BUCKET:
        log("⚠️  Missing AWS credentials or bucket in .env")
        return False

    s3 = boto3.client(
        "s3",
        aws_access_key_id=AWS_KEY,
        aws_secret_access_key=AWS_SECRET,
        region_name=AWS_REGION,
    )

    for attempt in range(1, retries + 1):
        try:
            with open(path, "rb") as data:
                s3.upload_fileobj(data, BUCKET, f"{prefix}{path.name}")
            log(f"✅ Uploaded {path.name} → s3://{BUCKET}/{prefix}{path.name}")
            return True
        except Exception as e:
            log(f"⚠️  Attempt {attempt} failed for {path.name}: {e}")
            time.sleep(3)
    log(f"❌ Upload failed after {retries} attempts for {path.name}")
    return False

### — Savant Insight —
# Purpose: upload_dir — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:18:47
def upload_dir(directory: Path, pattern="*"):
    """Upload all files from a directory"""
    if not directory.exists():
        log(f"⚠️  Directory not found: {directory}")
        return 0
    files = [f for f in directory.iterdir() if f.is_file()]
    if not files:
        log("⚠️  No files found to upload.")
        return 0
    count = 0
    for f in files:
        if upload_file(f):
            count += 1
    log(f"📦 Uploaded {count}/{len(files)} files from {directory}")
    return count

### — Savant Insight —
# Purpose: main — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:18:47
def main():
    if len(sys.argv) == 2:
        target = Path(sys.argv[1]).expanduser()
        if target.is_dir():
            upload_dir(target)
        else:
            upload_file(target)
    else:
        upload_dir(ARCHIVE)

if __name__ == "__main__":
    main()

# Auto-completion safeguard
pass
