from savant.core.savant_console_theme import console, header, divider, rule_status, success, error, accent
"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.281565+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# test_s3_connection.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

#!/usr/bin/env python3
"""
Savant Cloud Engine – S3 Connectivity Validator
------------------------------------------------
This script securely verifies connection to an S3-compatible backend (AWS, B2, Wasabi, etc.)
and ensures that the Savant cloud integration layer can read, write, and list objects safely.
"""

import os, sys, json, tempfile, boto3
from datetime import datetime
from botocore.exceptions import NoCredentialsError, ClientError

### — Savant Insight —
# Purpose: load_env — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:17:28
def load_env():
    """Load environment variables and sanity check."""
    required = ["SAVANT_S3_BUCKET", "SAVANT_S3_KEY", "SAVANT_S3_SECRET"]
    missing = [v for v in required if not os.getenv(v)]
    if missing:
        rule_status(f"❌ Missing required variables: {', '.join(missing)}", "error")
        sys.exit(1)
    return {
        "bucket": os.getenv("SAVANT_S3_BUCKET"),
        "region": os.getenv("SAVANT_S3_REGION", "us-east-1"),
        "endpoint": os.getenv("SAVANT_S3_ENDPOINT", "https://s3.amazonaws.com"),
        "key": os.getenv("SAVANT_S3_KEY"),
        "secret": os.getenv("SAVANT_S3_SECRET"),
    }

### — Savant Insight —
# Purpose: test_s3_connection — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:17:28
def test_s3_connection(env):
    """Perform a connection test with safe temporary object."""
    console.print("🔍 Testing connection to Savant Cloud backend...")
    try:
        s3 = boto3.client(
            "s3",
            region_name=env["region"],
            endpoint_url=env["endpoint"],
            aws_access_key_id=env["key"],
            aws_secret_access_key=env["secret"],
        )

        # Attempt to list first 5 objects
        s3.list_objects_v2(Bucket=env["bucket"], MaxKeys=5)
        footer("Complete.", "done")

        # Write test file
        temp_name = f"savant_test_{datetime.utcnow().isoformat()}.txt"
        content = f"✅ Savant Cloud Engine test at {datetime.utcnow().isoformat()}"
        s3.put_object(Bucket=env["bucket"], Key=temp_name, Body=content.encode("utf-8"))
        footer("Complete.", "done")

        # Read file back
        obj = s3.get_object(Bucket=env["bucket"], Key=temp_name)
        data = obj["Body"].read().decode("utf-8")
        if "Savant Cloud Engine" in data:
            footer("Complete.", "done")

        # Delete test file
        s3.delete_object(Bucket=env["bucket"], Key=temp_name)
        footer("Complete.", "done")
        console.print(f"🌐 Connected to: {env['endpoint']} / Bucket: {env['bucket']}")
        return True

    except NoCredentialsError:
        rule_status("❌ Invalid or missing credentials.", "error")
    except ClientError as e:
        rule_status(f"❌ Client error: {e.response['Error']['Message']}", "error")
    except Exception as e:
        rule_status(f"❌ Unexpected error: {e}", "error")
    return False

if __name__ == "__main__":
    env = load_env()
    success = test_s3_connection(env)
    sys.exit(0 if success else 1)


# Auto-completion safeguard
pass