"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.765700+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# dashboard_openapi_patch.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

from fastapi import APIRouter
import os, json, shutil
from datetime import datetime

router = APIRouter()

@router.post("/api/cloud/sync", tags=["Cloud"])
async def cloud_sync_patch():
    """
    Attempt S3 upload first; fallback to local archival sync.
    """
    bucket = os.getenv("SAVANT_S3_BUCKET", "savant-context")
    creds_path = os.path.expanduser("~/.savant/s3_credentials.json")
    research_dir = os.path.expanduser("~/savant/context/research")
    backup_dir = os.path.expanduser("~/savant/context/local_archive")
    uploaded = []

    # Try cloud first
    try:
        import boto3
        creds = json.load(open(creds_path))
        s3 = boto3.client(
            "s3",
            aws_access_key_id=creds["access_key"],
            aws_secret_access_key=creds["secret_key"]
        )
        for root, _, files in os.walk(research_dir):
            for f in files:
                path = os.path.join(root, f)
                key = f"research/{f}"
                s3.upload_file(path, bucket, key)
                uploaded.append(f)
        return {
            "mode": "cloud",
            "bucket": bucket,
            "uploaded": len(uploaded),
            "timestamp": datetime.now().isoformat()
        }
    except Exception as e:
        # Fallback: local archive mode
        os.makedirs(backup_dir, exist_ok=True)
        for root, _, files in os.walk(research_dir):
            for f in files:
                src = os.path.join(root, f)
                dst = os.path.join(backup_dir, f)
                shutil.copy2(src, dst)
                uploaded.append(f)
        return {
            "mode": "local",
            "reason": str(e),
            "archived_files": len(uploaded),
            "timestamp": datetime.now().isoformat()
        }