"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.766507+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# dashboard_openapi_patch_events.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

"""
Enhanced by Savant Clean+Complete Cluster v1.0 — 2025-10-30T06:11:07.931964+00:00
"""
from fastapi import APIRouter, Query
from savant.services.event_bus.event_bus_core import publish, replay_recent

router = APIRouter()

@router.get("/api/events/recent", tags=["Events"])
async def recent_events(limit: int = Query(20, ge=1, le=200)):
    """Return the most recent events."""
    return replay_recent(limit)

@router.post("/api/events/subscribe", tags=["Events"])
async def subscribe_event(type: str):
    """Fake subscription endpoint (placeholder for internal bridge)."""
    publish("subscription", {"type": type})
    return {"status": "ok", "type": type}