"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.765404+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# reflex_patch.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

from datetime import datetime
from pathlib import Path
import subprocess, shutil

### — Savant Insight —
# Purpose: get_cpu_safe — auto-annotated by Savant DocSynth
# Added 2025-10-30 20:06:08
def get_cpu_safe():
    """Return CPU percentage using top (Termux safe)."""
    try:
        out = subprocess.check_output(["top", "-n", "1", "-b"], text=True)
        for line in out.splitlines():
            if "CPU" in line or "Cpu(s)" in line:
                nums = [s for s in line.split() if "%" in s]
                if nums:
                    val = ''.join(ch for ch in nums[0] if ch.isdigit() or ch == '.')
                    return float(val)
        return 0.0
    except Exception:
        return 0.0

### — Savant Insight —
# Purpose: get_mem_safe — auto-annotated by Savant DocSynth
# Added 2025-10-30 20:06:08
def get_mem_safe():
    """Return memory percentage using free (Termux safe)."""
    try:
        out = subprocess.check_output(["free", "-m"], text=True)
        for line in out.splitlines():
            if line.lower().startswith("mem:"):
                parts = line.split()
                used, total = int(parts[2]), int(parts[1])
                return round((used / total) * 100, 1)
        return 0.0
    except Exception:
        return 0.0

### — Savant Insight —
# Purpose: reflex_validate_safe — auto-annotated by Savant DocSynth
# Added 2025-10-30 20:06:08
def reflex_validate_safe():
    context = Path.home() / "savant/context/context_ledger.json"
    issues = []
    if not context.exists():
        issues.append("context_ledger.json missing")

    cpu = get_cpu_safe()
    mem = get_mem_safe()
    disk = shutil.disk_usage("/")

    return {
        "timestamp": datetime.now().isoformat(),
        "issues": issues,
        "system": {
            "cpu": cpu,
            "mem": mem,
            "disk": round(disk.used / disk.total * 100, 1)
        }
    }