from savant.core.savant_console_theme import console, header, divider, rule_status, success, error, accent
"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.291327+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# context_ledger.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

#!/usr/bin/env python3
"""
Savant Context Ledger v3.0
An immutable, hierarchical, self-healing contextual memory.
"""

import orjson as json, time, uuid, os
from datetime import datetime
from pathlib import Path

ROOT    = Path.home()/"savant"
DOCS    = ROOT/"docs"
LEDGER  = DOCS/"context_ledger.json"
INDEX   = DOCS/"ledger_index.json"
BACKUP  = DOCS/"context_ledger.bak"
LOG     = ROOT/"logs/context_validator.log"

# --------------------------------------------------------------
# Utility
# --------------------------------------------------------------
### — Savant Insight —
# Purpose: utc — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:32:31
def utc(): return datetime.utcnow().isoformat()

### — Savant Insight —
# Purpose: read_json — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:32:31
def read_json(path,default=None):
    try: return json.loads(path.read_text())
    except: return default or {}

### — Savant Insight —
# Purpose: write_json — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:32:31
def write_json(path,data):
    path.parent.mkdir(parents=True,exist_ok=True)
    path.write_text(json.dumps(data,indent=2,ensure_ascii=False))

# 🔸 BEGIN_SNIPPET snippet_6 [f47d29375e]
<span style='color:#c7a740'>scan_elements(root: Path, recursive: bool):
    elements = []
    for dirpath, dirnames, filenames in os.walk(root):
        p = Path(dirpath)
        if any(p.iterdir()) and p != root:
            elements.append(p)
        if not recursive:
            break
    return elements</span>
# 🔸 END_SNIPPET
# --------------------------------------------------------------
# Core functions
# --------------------------------------------------------------
### — Savant Insight —
# Purpose: add_entry — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:32:31
def add_entry(scope:str,change_type:str,description:str,status:str="active",author:str="system"):
    """Append immutable context entry"""
    data = read_json(LEDGER,{"history":[],"summary":{}})
    entry = {
        "id": str(uuid.uuid4()),
        "timestamp": utc(),
        "scope": scope,
        "change_type": change_type,
        "description": description,
        "status": status,
        "author": author
    }
    data["history"].append(entry)
    data["summary"] = {
        "total_entries": len(data["history"]),
        "active": len([e for e in data["history"] if e["status"]=="active"]),
        "recent_scope": scope,
        "recent_change": change_type,
        "last_update": utc()
    }
    if LEDGER.exists(): BACKUP.write_text(LEDGER.read_text())
    write_json(LEDGER,data)
    return entry

### — Savant Insight —
# Purpose: build_index — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:32:31
def build_index():
    """Build searchable ledger index"""
    data = read_json(LEDGER,{"history":[]})
    index = {}
    for e in data["history"]:
        s=index.setdefault(e["scope"],[])
        s.append({"id":e["id"],"change":e["change_type"],"time":e["timestamp"]})
    write_json(INDEX,{"generated":utc(),"index":index})
    return index

# --------------------------------------------------------------
# Validator + Doctor
# --------------------------------------------------------------
### — Savant Insight —
# Purpose: validate_ledger — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:32:31
def validate_ledger():
    """Check coherence, mark anomalies"""
    data=read_json(LEDGER,{"history":[]})
    anomalies=[]
    scopes=set()
    for e in data["history"]:
        if e["scope"] in scopes and e["status"]=="active":
            pass
        scopes.add(e["scope"])
    # Detect duplicates or contradictions
    seen=set()
    for e in data["history"]:
        key=(e["scope"],e["change_type"])
        if key in seen:
            anomalies.append(f"Duplicate context event: {key}")
        seen.add(key)
    # Detect obsolete or conflicting statuses
    for e in data["history"]:
        if "deprecated" in e["description"].lower() and e["status"]=="active":
            anomalies.append(f"Obsolete entry still active: {e['id']}")
    if anomalies:
        LOG.write_text("\n".join([utc()]+anomalies))
        return False, anomalies
    return True, []

### — Savant Insight —
# Purpose: context_doctor — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:32:31
def context_doctor(anomalies):
    """Auto-repair simple contradictions"""
    data=read_json(LEDGER)
    fixed=0
    for e in data["history"]:
        for a in anomalies:
            if e["id"] in a or e["scope"] in a:
                e["status"]="deprecated"
                e["description"]+=" [auto-deprecated]"
                fixed+=1
    if fixed:
        write_json(LEDGER,data)
        build_index()
    return fixed

# --------------------------------------------------------------
# Retroactive bootstrap: populate historical context
# --------------------------------------------------------------
### — Savant Insight —
# Purpose: bootstrap_history — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:32:31
def bootstrap_history():
    if LEDGER.exists(): return
    console.print("🪶 Bootstrapping Savant contextual history...")
    history = [
        ("governance","initialization","Project rules imported and normalized."),
        ("hierarchy","revision","Expanded to 13-level fractal hierarchy."),
        ("hierarchy","app_inheritance","Apps begin at app level and inherit downward."),
        ("hierarchy","symbol_update","Shard level marked red hex; others gold/orange shades."),
        ("ui_template","creation","Savant baseline UI created (Next.js/Tailwind/Framer Motion/Three.js)."),
        ("version_system","implementation","Triadic version system with relational operators encoded as _lt_, _eq_, _gt_."),
        ("context_system","implementation","Immutable ledger introduced to ensure coherence."),
        ("enhancement_engine","policy_update","Enhancements run only after validation and project completion."),
        ("rule_system","integration","All non-negotiable rules integrated and propagated."),
        ("ai_core","centralization","Single OpenAI key and shared AI interface established."),
        ("task_engine","foundation","Dynamic nested task lattice created."),
        ("automation","daemon_init","Realtime watcher, self-diagnostic, master_guard launched."),
        ("branding","definition","Savant aesthetic defined: gunmetal + gold minimal industrial precision.")
    ]
    for scope,ct,desc in history: add_entry(scope,ct,desc)
    build_index()
    footer("Complete.", "done")

# --------------------------------------------------------------
# Main CLI
# --------------------------------------------------------------
### — Savant Insight —
# Purpose: main — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:32:31
def main():
    ok, issues = validate_ledger()
    if not ok:
        footer("Error.", "error")
        for i in issues: console.print(" -",i)
        fixed=context_doctor(issues)
        console.print(f"🔧 Auto-repaired {fixed} entries")
    else:
        footer("Complete.", "done")
    build_index()

if __name__=="__main__":
    bootstrap_history()
    main()

# Auto-completion safeguard
pass