from savant.core.savant_console_theme import console, header, divider, rule_status, success, error, accent
"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.301360+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# quality_gate.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

"""
Enhanced by Savant Clean+Complete Cluster v1.0 — 2025-10-30T06:11:07.501403+00:00
"""
# ~/savant/services/scripts/dependency_audit/quality_gate.py
import json, subprocess, sys

MIN_STARS = 5000
DISALLOWED = ["react", "vite", "tailwindcss", "redux", "next"]

### — Savant Insight —
# Purpose: get_repo_stars — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:41:32
def get_repo_stars(package):
    try:
        url = subprocess.check_output(
            ["npm", "view", package, "repository.url"], text=True
        ).strip().replace("git+", "").replace(".git", "")
        if "github.com" in url:
            owner_repo = url.split("github.com/")[1]
            api = f"https://api.github.com/repos/{owner_repo}"
            import requests
            data = requests.get(api).json()
            return data.get("stargazers_count", 0)
        return 0
    except Exception:
        return 0

### — Savant Insight —
# Purpose: audit — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:41:32
def audit():
    deps = json.loads(subprocess.check_output(["npm", "ls", "--json"], text=True))["dependencies"]
    failed = []
    for pkg in deps:
        if any(bad in pkg for bad in DISALLOWED):
            failed.append(f"{pkg} (banned)")
        stars = get_repo_stars(pkg)
        if stars < MIN_STARS:
            failed.append(f"{pkg} ({stars}★ < {MIN_STARS}★ required)")
    if failed:
        rule_status("❌ Failed quality gate:", "error")
        console.print("\n".join(f" - {f}" for f in failed))
        sys.exit(1)
    footer("Complete.", "done")

if __name__ == "__main__":
    audit()


# Auto-completion safeguard
pass