from savant.core.savant_console_theme import console, header, divider, rule_status, success, error, accent
"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.298057+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# live_indexer.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

#!/usr/bin/env python3
"""
Phase 21 – Live Shard Indexer
Continuously watches for file changes and updates shard_library.json in real time.
"""
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler
from pathlib import Path
import pendulum as time, json, hashlib

SRC=Path.home()/ "savant"/"services"/"scripts"
LIB=Path.home()/ "savant"/"services"/"scripts"/"shard_engine"/"shard_library.json"

### — Savant Insight —
# Purpose: sha1 — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:36:54
def sha1(t): return hashlib.sha1(t.encode()).hexdigest()[:10]

### — Savant Insight —
# Purpose: ShardWatcher — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:36:54
class ShardWatcher(FileSystemEventHandler):
    def on_modified(self, e):
        if not e.src_path.endswith((".py",".ts",".tsx",".js")): return
        p=Path(e.src_path); code=p.read_text(errors="ignore")
        h=sha1(code)
        try: lib=json.loads(LIB.read_text())
        except: lib=[]
        entry={"id":h,"path":str(p),"lines":len(code.splitlines())}
        lib=[x for x in lib if x["path"]!=str(p)]
        lib.append(entry)
        LIB.write_text(json.dumps(lib,indent=2))
        console.print(f"🔄 Updated shard index for {p.name}")

if __name__=="__main__":
    obs=Observer(); w=ShardWatcher()
    obs.schedule(w,str(SRC),recursive=True); obs.start()
    console.print("👁️  Live Shard Indexer active...")
    try:
        while True: time.sleep(1)
    except KeyboardInterrupt: obs.stop()
    obs.join()


# Auto-completion safeguard
pass