from savant.core.savant_console_theme import console, header, divider, rule_status, success, error, accent
"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.298700+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# semantic_search.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

#!/usr/bin/env python3
"""
Phase 24 – Semantic Shard Search
Allows natural language queries over shard library.
"""
from openai import OpenAI
import os, json
from pydantic_settings import BaseSettings
from pathlib import Path

load_dotenv(Path.home() / "savant" / ".env")/".env")
client=OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
LIB=Path.home()/ "savant"/"services"/"scripts"/"shard_engine"/"shard_library.json"

### — Savant Insight —
# Purpose: query — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:37:50
def query(q):
    shards=json.loads(LIB.read_text())
    joined="\n".join([s["content"][:200] for s in shards])
    res=client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role":"system","content":"You are a code librarian."},
            {"role":"user","content":f"Find shards relevant to '{q}' from:\n{joined}"}
        ])
    console.print(res.choices[0].message.content)

if __name__=="__main__":
    q=input("🔍 Describe what you're looking for: ")
    query(q)


# Auto-completion safeguard
pass