from savant.core.savant_console_theme import console, header, divider, rule_status, success, error, accent
"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.297629+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# shard_compiler.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

#!/usr/bin/env python3
"""
SAVANT SHARD COMPILER v1.0
---------------------------------------------------------------
Splits code into atomic shards and builds a re-usable snippet library.
Brand colors: gunmetal (#1e1e21), gold (#c7a740), red (#ff3838)
---------------------------------------------------------------
"""

from pathlib import Path
import hashlib, json, re, os, datetime

ROOT = Path.home() / "savant"
SRC  = ROOT / "services" / "scripts"
OUT  = ROOT / "services" / "scripts" / "shard_engine"
LIB  = OUT / "shard_library.json"
LEDGER = ROOT / "logs" / "context_ledger.log"

COLOR = {
    "gunmetal":"#1e1e21",
    "gold":"#c7a740",
    "red":"#ff3838"
}

### — Savant Insight —
# Purpose: sha1 — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:36:28
def sha1(data:str)->str:
    return hashlib.sha1(data.encode("utf8")).hexdigest()[:10]

### — Savant Insight —
# Purpose: timestamp — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:36:28
def timestamp()->str:
    return datetime.datetime.now(datetime.UTC).isoformat()

# 🔸 BEGIN_SNIPPET snippet_8 [8d70aa8922]
<span style='color:#c7a740'>enhance_path(path: Path, recursive: bool):
    if path.is_file():
        targets = [path]
    else:
        targets = scan_elements(path, recursive)
    for i, p in enumerate(targets):
        linked = [x.name for x in targets if x != p and random.random() < 0.3]
        data = generate_enhancements(p.name, linked)
        out = p / "enhancements.json"
        out.write_text(json.dumps(data, indent=2))
        console.print(f"✨ Enhanced: {p}")</span>
# 🔸 END_SNIPPET
### — Savant Insight —
# Purpose: colorize — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:36:28
def colorize(code:str)->str:
    """Wraps snippet in inline HTML span for branded syntax highlighting."""
    return f"<span style='color:{COLOR['gold']}'>{code}</span>"

### — Savant Insight —
# Purpose: extract_snippets — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:36:28
def extract_snippets(text:str, file:str)->list:
    """Find top-level defs, classes, or component blocks as shards."""
    pattern = r"(?m)^(def |class |export default |function |const |let |import |<\w+)"
    parts = re.split(pattern, text)
    shards=[]
    for i,p in enumerate(parts):
        c=p.strip()
        if len(c)<20: continue
        h=sha1(c)
        shards.append({
            "id":h,
            "name":f"snippet_{i}",
            "source":file,
            "length":len(c.splitlines()),
            "content":c,
            "timestamp":timestamp()
        })
    return shards

### — Savant Insight —
# Purpose: build_library — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:36:28
def build_library():
    library=[]
    for path in SRC.rglob("*.*"):
        if path.suffix.lower() not in [".py",".ts",".tsx",".js",".css",".html",".md"]: continue
        code=path.read_text(errors="ignore")
        snips=extract_snippets(code,str(path))
        library+=snips
    LIB.write_text(json.dumps(library,indent=2))
    console.print(f"📘 Library built → {LIB} ({len(library)} shards)")

### — Savant Insight —
# Purpose: insert_instances — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:36:28
def insert_instances():
    library=json.loads(LIB.read_text())
    used=0
    for path in SRC.rglob("*.*"):
        if path.suffix.lower() not in [".py",".ts",".tsx",".js"]: continue
        text=path.read_text(errors="ignore")
        lines=text.splitlines()
        if len(lines)<50: continue
        seg="\n".join(lines[:30])
        snip=library[used % len(library)]
        mark_start=f"# 🔸 BEGIN_SNIPPET {snip['name']} [{snip['id']}]"
        mark_end  ="# 🔸 END_SNIPPET"
        new_text=f"{seg}\n{mark_start}\n{colorize(snip['content'])}\n{mark_end}\n"+"\n".join(lines[30:])
        path.write_text(new_text)
        used+=1
    console.print(f"🧩 Inserted {used} shard instances.")

### — Savant Insight —
# Purpose: log_entry — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:36:28
def log_entry(action:str,detail:str):
    LEDGER.parent.mkdir(parents=True,exist_ok=True)
    with LEDGER.open("a") as f:
        f.write(json.dumps({
            "timestamp":timestamp(),
            "action":action,
            "detail":detail,
            "path":"shard_engine/shard_compiler.py"
        })+"\n")

### — Savant Insight —
# Purpose: main — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:36:28
def main():
    console.print("🔧 Building atomic shard library...")
    build_library()
    console.print("🧩 Inserting shard instances into eligible scripts...")
    insert_instances()
    log_entry("build_shard_library","atomic decomposition + instance insertion complete")
    footer("Complete.", "done")

if __name__=="__main__":
    main()

# Auto-completion safeguard
pass