"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.283756+00:00
"""
# ===============================================================
# __init__.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

"""
Enhanced by Savant Clean+Complete Cluster v1.0 — 2025-10-30T06:11:07.451481+00:00
"""
from pathlib import Path
import subprocess, sys
def check_rules():
    enforcer = Path.home()/ "savant/services/scripts/rule_engine/enforcer.py"
    subprocess.run([sys.executable, str(enforcer)], check=True)


# Auto-completion safeguard
pass
