from savant.core.savant_console_theme import console, header, divider, rule_status, success, error, accent
"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.283388+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# enforcer.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

"""
Enhanced by Savant Clean+Complete Cluster v1.0 — 2025-10-30T06:11:07.445648+00:00
"""
#!/usr/bin/env python3
import orjson as json, re, sys
from pathlib import Path
from datetime import datetime, timezone

ROOT = Path.home()/ "savant"
DOCS = ROOT/"docs"
RULES = DOCS/"PROJECT_RULES.md"
INDEX = DOCS/"rules_manifest.json"
REF_PATH = DOCS/"ref_counter.json"

# --- reference numbering --------------------------------------
### — Savant Insight —
# Purpose: next_ref — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:19:50
def next_ref():
    REF_PATH.parent.mkdir(parents=True, exist_ok=True)
    ref = {"post":0,"line":0}
    if REF_PATH.exists():
        ref = json.loads(REF_PATH.read_text())
    ref["post"] += 1
    ref["line"] = 0
    REF_PATH.write_text(json.dumps(ref))
    return f"{ref['post']:04d}"

### — Savant Insight —
# Purpose: next_line_ref — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:19:50
def next_line_ref():
    ref = json.loads(REF_PATH.read_text())
    ref["line"] += 1
    REF_PATH.write_text(json.dumps(ref))
    return f"{ref['post']:04d}.{ref['line']:03d}"

# --- rule extraction ------------------------------------------
### — Savant Insight —
# Purpose: parse_rules — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:19:50
def parse_rules():
# 🔸 BEGIN_SNIPPET snippet_4 [0a6da6c8e7]
<span style='color:#c7a740'>generate(module_path:str):
    p=Path(module_path); modname=p.stem
    mod=importlib.import_module(f"savant.services.scripts.{p.parent.name}.{modname}")
    funcs=[f for _,f in inspect.getmembers(mod,inspect.isfunction)]
    rendered=TEMPLATE.render(
        name=modname,
        ts=datetime.datetime.utcnow().isoformat(),
        summary=textwrap.dedent(inspect.getdoc(mod) or "savant module"),
        funcs=[{"name":f.__name__,"doc":textwrap.dedent(inspect.getdoc(f) or "undocumented")} for f in funcs]
    )
    out=p.with_suffix('.README.md'); out.write_text(rendered)
    return out</span>
# 🔸 END_SNIPPET
    if not RULES.exists():
        raise FileNotFoundError("PROJECT_RULES.md missing")
    data = RULES.read_text().splitlines()
    rules = []
    cur = None
    for line in data:
        if re.match(r"^\d+\.", line.strip()):
            if cur: rules.append(cur)
            num, text = line.split(".",1)
            cur = {"id":num.strip(),"rule":text.strip()}
        elif cur and line.strip():
            cur["rule"] += " "+line.strip()
    if cur: rules.append(cur)
    return rules

# --- rule manifest sync ---------------------------------------
### — Savant Insight —
# Purpose: sync_manifest — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:19:50
def sync_manifest():
    rules = parse_rules()
    manifest = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "count": len(rules),
        "rules": rules
    }
    INDEX.write_text(json.dumps(manifest, indent=2))
    footer("Complete.", "done")

# --- enforcement hook -----------------------------------------
### — Savant Insight —
# Purpose: enforce — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:19:50
def enforce():
    if not INDEX.exists():
        sync_manifest()
    manifest = json.loads(INDEX.read_text())
    now = datetime.now(timezone.utc)
    ts = datetime.fromisoformat(manifest["timestamp"])
    age = (now - ts).total_seconds() / 3600
    if age > 24:
        rule_status("❌ Rule set outdated (>24h) — update required.", "error")
        sys.exit(1)
    console.print(f"🧱 Savant Enforcement Active — {len(manifest['rules'])} directives loaded.")

if __name__=="__main__":
    if len(sys.argv)>1 and sys.argv[1]=="sync":
        sync_manifest()
    else:
        enforce()

# Auto-completion safeguard
pass