from savant.core.savant_console_theme import console, header, divider, rule_status, success, error, accent
"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.283008+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# rule_guard.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

"""
Enhanced by Savant Clean+Complete Cluster v1.0 — 2025-10-30T06:11:07.441541+00:00
"""
import os, time, json
from datetime import datetime
from pathlib import Path
ROOT=Path.home()/ "savant"
RULES=ROOT/"docs/PROJECT_RULES.md"
if not RULES.exists():
    raise SystemExit("❌ RULES FILE MISSING — EXECUTION HALTED")

stamp = RULES.stat().st_mtime
age = (time.time()-stamp)/3600
if age>24:
    raise SystemExit("⏱ RULES OUTDATED — Update required")

console.print(f"🧱 RULE ENFORCEMENT OK @ {datetime.utcnow().isoformat()}")


# Auto-completion safeguard
pass