from savant.core.savant_console_theme import console, header, divider, rule_status, success, error, accent
"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.736438+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# ai_link_adapter.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

```python
import os
import json
import requests

### — Savant Insight —
# Purpose: link_test — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:45:47
def link_test(prompt="Summarize the purpose of Savant AI."):
    """
    Sends a prompt to the Savant AI endpoint and prints the response.

    Args:
        prompt (str): The prompt to send to the AI. Defaults to a summary request for Savant AI.

    Returns:
        None
    """
    endpoint = "http://127.0.0.1:7070/api/ai"
    payload = {"prompt": prompt}

    try:
        # Sending a POST request to the AI endpoint with the provided prompt
        res = requests.post(endpoint, json=payload, timeout=20)
        res.raise_for_status()  # Raise an error for bad responses (4xx and 5xx)
        console.print("🔗 Savant → AI link response:", res.text[:400])  # Print the first 400 characters of the response
    except requests.exceptions.RequestException as e:
        # Handle any request-related errors
        console.print("⚠ AI link failed:", e)

if __name__ == "__main__":
    # Execute the link_test function when the script is run directly
    link_test()
```

# Auto-completion safeguard
pass
