from savant.core.savant_console_theme import console, header, divider, rule_status, success, error, accent
"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.737474+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# auto_learning_supervisor.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

#!/usr/bin/env python3
"""
SAVANT AUTO-LEARNING SUPERVISOR (patched)
- Tracks cycles in ~/savant/context/auto_learning_state.json
- Every 3 cycles runs compact_shards.py to prune historical shard variants.
- Falls back gracefully if compactor or context dir missing.
"""
import os, json, subprocess
from pathlib import Path
from datetime import datetime

BASE = Path("~/savant").expanduser()
CTX = BASE / "context"
CTX.mkdir(parents=True, exist_ok=True)
STATE = CTX / "auto_learning_state.json"
COMPACTOR = Path("~/savant/services/scripts/intelligence_cluster/compact_shards.py").expanduser()

### — Savant Insight —
# Purpose: load_state — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:48:07
def load_state():
    if STATE.exists():
        try:
            return json.loads(STATE.read_text())
        except Exception:
            pass
    return {"cycles": 0, "last_run": None}

### — Savant Insight —
# Purpose: save_state — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:48:07
def save_state(s):
    STATE.write_text(json.dumps(s, indent=2))

### — Savant Insight —
# Purpose: maybe_compact — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:48:07
def maybe_compact(cycles):
    if cycles % 3 != 0:
        return False, "skip"
    if not COMPACTOR.exists():
        return False, "compactor_missing"
    try:
        # Keep only newest per stem, move older to trash
        cmd = ["python3", str(COMPACTOR), "--keep", "1"]
        out = subprocess.check_output(cmd, stderr=subprocess.STDOUT, text=True)
        return True, out
    except subprocess.CalledProcessError as e:
        return False, f"error: {e.output}"
    except Exception as e:
        return False, f"exception: {e}"

### — Savant Insight —
# Purpose: main — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:48:07
def main():
    st = load_state()
    st["cycles"] = st.get("cycles", 0) + 1
    st["last_run"] = datetime.now().isoformat()

    compacted, info = maybe_compact(st["cycles"])
    save_state(st)

    header("Savant Core", "1.0", "Restored aesthetic", "core")
    if compacted:
        console.print("🧹 Compact Mode triggered:\n" + info)
    else:
        console.print(f"ℹ️  Compact Mode: {info}")

if __name__ == "__main__":
    main()

# Auto-completion safeguard
pass
