from savant.core.savant_console_theme import console, header, divider, rule_status, success, error, accent
"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.740356+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# bootstrap_cluster.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

#!/usr/bin/env python3
"""
SAVANT AUTONOMOUS BOOTSTRAP CLUSTER v5.0
----------------------------------------
Boots Savant, verifies connections, performs housekeeping,
and triggers AI, cloud, and GitHub sync automatically.
"""

import os, sys, subprocess, shutil, json, time
from datetime import datetime, timezone, timedelta
from pathlib import Path

BASE = Path.home() / "savant"
LOG = BASE / "logs" / "bootstrap.log"
EXPORT_SCRIPT = BASE / "services" / "scripts" / "intelligence_cluster" / "export_cluster_v5_1.py"
MIGRATION_SCRIPT = BASE / "services" / "scripts" / "intelligence_cluster" / "migration_check_cluster.py"
KNOWLEDGE_SCRIPT = BASE / "services" / "scripts" / "intelligence_cluster" / "knowledge_synthesis_cluster.py"
GIT_PUSH_SCRIPT = BASE / "services" / "scripts" / "intelligence_cluster" / "github_force_push.py"
CLOUD_UPLINK = BASE / "services" / "scripts" / "cloud_engine" / "cloud_uplink.py"

### — Savant Insight —
# Purpose: log — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:53:34
def log(msg):
    ts = datetime.now(timezone.utc).isoformat()
    line = f"[{ts}] {msg}"
    console.print(line)
    LOG.parent.mkdir(parents=True, exist_ok=True)
    with open(LOG, "a") as f:
        f.write(line + "\n")

### — Savant Insight —
# Purpose: run — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:53:34
def run(cmd, desc):
    log(f"▶ {desc}")
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, check=True)
        log(result.stdout.strip() or "(no output)")
    except subprocess.CalledProcessError as e:
        log(f"⚠ {desc} failed:\n{e.stderr.strip()}")

### — Savant Insight —
# Purpose: clean_temp — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:53:34
def clean_temp():
    """Deep clean of temporary folders."""
    log("🧹 Cleaning temporary and cache files...")
    removed = 0
    for pattern in ["*.log", "*.tmp", "__pycache__", ".pytest_cache"]:
        for p in BASE.rglob(pattern):
            try:
                if p.is_file():
                    p.unlink()
                    removed += 1
                elif p.is_dir():
                    shutil.rmtree(p, ignore_errors=True)
                    removed += 1
            except Exception:
                pass
    log(f"✅ Removed {removed} redundant items.")
    return removed

### — Savant Insight —
# Purpose: check_connections — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:53:34
def check_connections():
    """Verify core integrations: OpenAI, GitHub, and S3."""
    log("🔗 Verifying connections...")
    try:
        run(["python3", str(MIGRATION_SCRIPT)], "Check OpenAI + GitHub + S3 connectivity")
    except Exception as e:
        log(f"⚠ Connectivity test failed: {e}")

### — Savant Insight —
# Purpose: run_compaction — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:53:34
def run_compaction():
    """Invoke export/compaction cycle."""
    log("📦 Running export + compaction cycle...")
    try:
        run(["python3", str(EXPORT_SCRIPT)], "Run export_cluster_v5_1.py")
    except Exception as e:
        log(f"⚠ Export failed: {e}")

### — Savant Insight —
# Purpose: sync_github — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:53:34
def sync_github():
    """Force push current state to GitHub."""
    log("🐙 Syncing GitHub repository...")
    try:
        run(["python3", str(GIT_PUSH_SCRIPT)], "GitHub Force Push")
    except Exception as e:
        log(f"⚠ GitHub sync failed: {e}")

### — Savant Insight —
# Purpose: sync_cloud — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:53:34
def sync_cloud():
    """Upload archives and logs to S3."""
    log("☁️ Uploading archives and logs to cloud...")
    archive_dir = BASE / "archive"
    if not archive_dir.exists():
        log("⚠ No archive directory found, skipping cloud sync.")
        return
    for item in archive_dir.iterdir():
        if item.is_file():
            run(["python3", str(CLOUD_UPLINK), str(item)], f"Upload {item.name}")

### — Savant Insight —
# Purpose: synthesize_knowledge — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:53:34
def synthesize_knowledge():
    """Rebuild modular AI knowledge shards."""
    log("📚 Running knowledge synthesis cluster...")
    try:
        run(["python3", str(KNOWLEDGE_SCRIPT)], "Knowledge synthesis")
    except Exception as e:
        log(f"⚠ Knowledge synthesis failed: {e}")

### — Savant Insight —
# Purpose: main — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:53:34
def main():
    log(f"🧠 Starting Savant Autonomous Bootstrap Cycle at {datetime.now(timezone.utc).isoformat()}")
    os.chdir(BASE)

    # 1. Cleanup
    clean_temp()

    # 2. Connection checks
    check_connections()

    # 3. Knowledge synthesis
    synthesize_knowledge()

    # 4. Export + compaction
    run_compaction()

    # 5. GitHub + Cloud sync
    sync_github()
    sync_cloud()

    # 6. Completion summary
    log("✅ Bootstrap cycle complete.")
    footer("Complete.", "done")

if __name__ == "__main__":
    main()

# Auto-completion safeguard
pass
