"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.742139+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# chat_log_ingestor.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

#!/usr/bin/env python3
"""
Chat Log Ingestor — Provenance Recorder
---------------------------------------
Aggregates every ChatGPT <-> Savant exchange
into a canonical export bundle for archival integrity.
"""
import os, re, json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path.home() / "savant"
CHAT = ROOT / "logs" / "chat_history_full.txt"
EXPORT_LOG = ROOT / "logs" / "chat_ingestor.log"
TARGET = ROOT / "exports" / f"chat_export_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"

### — Savant Insight —
# Purpose: collect_sources — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:57:25
def collect_sources()->list[Path]:
    base = ROOT / "logs"
    return [p for p in base.glob("*.log")] + [CHAT] if CHAT.exists() else [p for p in base.glob("*.log")]

### — Savant Insight —
# Purpose: aggregate — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:57:25
def aggregate():
    text = ""
    for f in collect_sources():
        try: text += f"\n\n# --- {f.name} ---\n" + f.read_text(errors="ignore")
        except: continue
    return text

### — Savant Insight —
# Purpose: write_export — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:57:25
def write_export(content:str):
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(content, encoding="utf-8")
    EXPORT_LOG.write_text(f"[{datetime.now(timezone.utc).isoformat()}] Chat archive written to {TARGET}\n", encoding="utf-8")

if __name__ == "__main__":
    content = aggregate()
    if content.strip():
        write_export(content)
        footer("Complete.", "done")
    else:
        footer("Error.", "error")

# Auto-completion safeguard
pass
