from savant.core.savant_console_theme import console, header, divider, rule_status, success, error, accent
"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.739004+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# cloud_recover.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

#!/usr/bin/env python3
"""
SAVANT CLOUD RECOVERY v1.0
Downloads and restores the latest S3 export archive automatically.
"""
import os, boto3, zipfile, shutil
from datetime import datetime
from pathlib import Path
from dotenv import load_dotenv

BASE = Path.home() / "savant"
EXPORTS = BASE / "archive"
EXPORTS.mkdir(parents=True, exist_ok=True)
load_dotenv(BASE / ".env")

### — Savant Insight —
# Purpose: get_s3 — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:50:41
def get_s3():
    return boto3.client(
        "s3",
        aws_access_key_id=os.getenv("AWS_ACCESS_KEY_ID"),
        aws_secret_access_key=os.getenv("AWS_SECRET_ACCESS_KEY"),
        region_name=os.getenv("AWS_DEFAULT_REGION", "us-east-1")
    )

### — Savant Insight —
# Purpose: download_latest — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:50:41
def download_latest():
    bucket = os.getenv("SAVANT_S3_BUCKET")
    if not bucket:
        footer("Error.", "error")
        return None
    s3 = get_s3()
    objs = s3.list_objects_v2(Bucket=bucket, Prefix="exports/")
    if "Contents" not in objs:
        footer("Error.", "error")
        return None
    latest = max(objs["Contents"], key=lambda x: x["LastModified"])
    key = latest["Key"]
    local = EXPORTS / Path(key).name
    console.print(f"⬇️  Downloading {key} → {local}")
    s3.download_file(bucket, key, str(local))
    footer("Complete.", "done")
    return local

### — Savant Insight —
# Purpose: restore_archive — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:50:41
def restore_archive(archive_path: Path):
    dest = BASE
    console.print(f"🧩 Restoring archive → {dest}")
    with zipfile.ZipFile(archive_path, "r") as zf:
        zf.extractall(dest)
    footer("Complete.", "done")

if __name__ == "__main__":
    header("Savant Core", "1.0", "Restored aesthetic", "core")
    latest = download_latest()
    if latest:
        restore_archive(latest)
        footer("Complete.", "done")
    else:
        footer("Error.", "error")

# Auto-completion safeguard
pass
