"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.741280+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# cloud_uplink.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

"""
CLOUD UPLINK — v2.0
Uploads knowledge artifacts to S3 (requires AWS_* vars and SAVANT_S3_BUCKET).
"""
import os, pathlib, boto3
from botocore.config import Config
from datetime import datetime, timezone

BASE = pathlib.Path(os.path.expanduser("~/savant"))
KDIR = BASE / "knowledge"
LOGS = BASE / "logs"
BUCKET = os.getenv("SAVANT_S3_BUCKET", "")

### — Savant Insight —
# Purpose: iso — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:55:41
def iso():
    return datetime.now(timezone.utc).isoformat()

### — Savant Insight —
# Purpose: s3 — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:55:41
def s3():
    return boto3.client("s3",
        aws_access_key_id=os.getenv("AWS_ACCESS_KEY_ID"),
        aws_secret_access_key=os.getenv("AWS_SECRET_ACCESS_KEY"),
        region_name=os.getenv("AWS_DEFAULT_REGION","us-east-1"),
        config=Config(signature_version="s3v4", retries={"max_attempts":3})
    )

### — Savant Insight —
# Purpose: upload_dir — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:55:41
def upload_dir(local_dir: pathlib.Path, prefix: str):
    c = s3()
    sent = 0
    for fp in local_dir.rglob("*"):
        if fp.is_dir(): continue
        key = f"{prefix}/{fp.relative_to(local_dir).as_posix()}"
        c.upload_file(str(fp), BUCKET, key)
        sent += 1
    return sent

### — Savant Insight —
# Purpose: main — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:55:41
def main():
    if not BUCKET:
        footer("Error.", "error")
        return
    sent = 0
    sent += upload_dir(KDIR / "shards", "knowledge/shards")
    sent += upload_dir(KDIR / "meta",   "knowledge/meta")
    footer("Complete.", "done")
    (LOGS / "cloudbridge.log").open("a").write(f"[{iso()}] uploaded {sent}\n")

if __name__ == "__main__":
    main()

# Auto-completion safeguard
pass
