from savant.core.savant_console_theme import console, header, divider, rule_status, success, error, accent
"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.736688+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# cluster_supervisor.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

```python
import os
import json
import subprocess
import time
from datetime import datetime, timezone

### — Savant Insight —
# Purpose: run — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:46:17
def run(command):
    """
    Executes a shell command and prints the command being executed.

    Args:
        command (str): The command to be executed in the shell.

    Returns:
        int: The return code from the command execution.
    """
    console.print(f"▶ {command}")
    return subprocess.call(command, shell=True)

### — Savant Insight —
# Purpose: run_cluster — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:46:17
def run_cluster():
    """
    Main function to supervise the Savant cluster. It verifies enhancements
    and checks the AI link by executing the corresponding scripts.
    """
    header("Savant Core", "1.0", "Restored aesthetic", "core")
    
    # Phase check: verifying enhancements
    console.print("Phase check: verifying enhancements + AI link...")
    
    # Run enhancement verification script
    enhancement_script = "python3 ~/savant/services/scripts/intelligence_cluster/verify_enhancements.py"
    if run(enhancement_script) != 0:
        rule_status("❌ Enhancement verification failed.", "error")
        return
    
    time.sleep(2)  # Pause for stability

    # Run AI link adapter script
    ai_link_script = "python3 ~/savant/services/scripts/intelligence_cluster/ai_link_adapter.py"
    if run(ai_link_script) != 0:
        rule_status("❌ AI link adapter execution failed.", "error")
        return

    footer("Complete.", "done")

if __name__ == "__main__":
    run_cluster()
```

# Auto-completion safeguard
pass
