from savant.core.savant_console_theme import console, header, divider, rule_status, success, error, accent
"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.738627+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# compact_shards.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

#!/usr/bin/env python3
"""
SAVANT COMPACTOR v2.1
Safely compacts historical versioned shard files like:
  name_713549_10-28-25.py
Keeps the newest per "stem" and archives older ones.
- Default: move old variants to ~/savant/archive/trash/<ts> (safe).
- --delete: permanently delete instead of moving to trash.
- --keep N: keep N most-recent variants per stem (default 1).
- --dry-run: report without changing anything.
- --root PATH: override scan root (default: ~/savant/services/scripts)
"""
import re, os, sys, shutil, json, time
from pathlib import Path
from datetime import datetime

ROOT = Path(os.environ.get("SAVANT_SCRIPTS_ROOT", "~/savant/services/scripts")).expanduser()
TRASH_BASE = Path("~/savant/archive/trash").expanduser()
LOG_DIR = Path("~/savant/logs").expanduser()
LOG_DIR.mkdir(parents=True, exist_ok=True)
LOG_PATH = LOG_DIR / "compact_shards.log.jsonl"

# Matches ".../<anything>/<stem>_<seq>_<MM>-<DD>-<YY>.py"
PAT = re.compile(r"^(?P<stem>.+)_(?P<seq>\d{3,})_(?P<date>\d{2}-\d{2}-\d{2})\.py$")

### — Savant Insight —
# Purpose: parse_variant — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:50:18
def parse_variant(file: Path):
    m = PAT.match(file.name)
    if not m:
        return None
    stem = m.group("stem")
    seq = int(m.group("seq"))
    date_str = m.group("date")  # MM-DD-YY
    try:
        # Normalize to sortable tuple: (YY, MM, DD) to avoid 2000 vs 1900 ambiguity
        mm, dd, yy = [int(x) for x in date_str.split("-")]
        # assume 20xx (works for current project dates)
        year = 2000 + yy
        dt = datetime(year, mm, dd)
        key = (year, mm, dd, seq, file.stat().st_mtime)
    except Exception:
        # Fallback to mtime
        key = (0, 0, 0, seq, file.stat().st_mtime)
    return stem, key

### — Savant Insight —
# Purpose: list_variants — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:50:18
def list_variants(root: Path):
    groups = {}
    for p in root.rglob("*.py"):
        info = parse_variant(p)
        if info:
            stem, sort_key = info
            groups.setdefault(stem, []).append((p, sort_key))
    return groups

### — Savant Insight —
# Purpose: ensure_trash — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:50:18
def ensure_trash():
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    d = TRASH_BASE / ts
    d.mkdir(parents=True, exist_ok=True)
    return d

### — Savant Insight —
# Purpose: log_event — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:50:18
def log_event(kind, payload):
    LOG_DIR.mkdir(parents=True, exist_ok=True)
    with open(LOG_PATH, "a") as f:
        f.write(json.dumps({
            "time": datetime.now().isoformat(),
            "kind": kind,
            **payload
        }) + "\n")

### — Savant Insight —
# Purpose: main — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:50:18
def main():
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=str(ROOT), help="Scan root (default: ~/savant/services/scripts)")
    ap.add_argument("--keep", type=int, default=1, help="Keep newest N variants per stem")
    ap.add_argument("--delete", action="store_true", help="Permanently delete old variants (default: move to trash)")
    ap.add_argument("--dry-run", action="store_true", help="Report only, no changes")
    args = ap.parse_args()

    root = Path(args.root).expanduser()
    if not root.exists():
        rule_status(f"❌ Root not found: {root}", "error")
        sys.exit(1)

    groups = list_variants(root)
    stems = len(groups)
    total_variants = sum(len(v) for v in groups.values())

    will_remove = []
    for stem, items in groups.items():
        items.sort(key=lambda x: x[1], reverse=True)  # newest first by (year, mm, dd, seq, mtime)
        to_remove = items[args.keep:]
        will_remove.extend([p for (p, _) in to_remove])

    console.print(f"📦 Found {stems} stems with {total_variants} versioned variants.")
    console.print(f"🗂  Will retain {sum(min(len(v), args.keep) for v in groups.values())} and remove {len(will_remove)}.")

    if args.dry_run:
        for p in will_remove[:50]:
            console.print(f"  - would remove: {p}")
        if len(will_remove) > 50:
            console.print(f"  ... and {len(will_remove)-50} more")
        return

    removed = 0
    if args.delete:
        for p in will_remove:
            try:
                p.unlink()
                removed += 1
            except Exception as e:
                footer("Error.", "error")
    else:
        trash_dir = ensure_trash()
        for p in will_remove:
            try:
                rel = p.relative_to(root)
                dest_dir = trash_dir / rel.parent
                dest_dir.mkdir(parents=True, exist_ok=True)
                shutil.move(str(p), str(dest_dir / p.name))
                removed += 1
            except Exception as e:
                footer("Error.", "error")

    footer("Complete.", "done")
    log_event("compact_complete", {
        "root": str(root),
        "stems": stems,
        "total_variants": total_variants,
        "removed": removed,
        "mode": "delete" if args.delete else "trash"
    })

if __name__ == "__main__":
    main()

# Auto-completion safeguard
pass
