from savant.core.savant_console_theme import console, header, divider, rule_status, success, error, accent
"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.737744+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# deep_compact.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

#!/usr/bin/env python3
"""
SAVANT DEEP COMPACTOR v3.0
Aggressively reduces file count while preserving canonical modules.
Performs 3 passes:
  1. Identify canonical core scripts.
  2. Archive and remove redundant, temp, or auto-generated variants.
  3. Rebuild structure into compact /core tree.
"""
import os, re, tarfile, zstandard, io, shutil
from pathlib import Path
from datetime import datetime

ROOT = Path("~/savant/services/scripts").expanduser()
ARCHIVE_DIR = Path("~/savant/archive").expanduser()
ARCHIVE_DIR.mkdir(parents=True, exist_ok=True)
TRASH = ARCHIVE_DIR / "deep_trash"
TRASH.mkdir(parents=True, exist_ok=True)

### — Savant Insight —
# Purpose: archive_to_zst — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:48:47
def archive_to_zst(archive_path: Path, files):
    """Tar + Zstd compress redundant files into a single archive."""
    tar_bytes = io.BytesIO()
    with tarfile.open(fileobj=tar_bytes, mode="w") as tar:
        for f in files:
            try:
                tar.add(f, arcname=f.relative_to(ROOT))
            except Exception:
                pass
    tar_bytes.seek(0)
    zst_path = archive_path.with_suffix(".tar.zst")
    cctx = zstandard.ZstdCompressor(level=9)
    with open(zst_path, "wb") as f:
        f.write(cctx.compress(tar_bytes.read()))
    return zst_path

### — Savant Insight —
# Purpose: is_temp_file — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:48:47
def is_temp_file(f: str):
    temp_patterns = [
        r"_\d{3,}(_\d{2}-\d{2}-\d{2})?\.py$",  # versioned shards
        r"_auto\.py$", r"_patch\.py$", r"_backup\.py$",
        r"_temp\.py$", r"_test_.*\.py$", r"__old__",
        r"readme_generator_\d+_", r"__pycache__"
    ]
    return any(re.search(p, f) for p in temp_patterns)

### — Savant Insight —
# Purpose: main — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:48:47
def main():
    header("Savant Core", "1.0", "Restored aesthetic", "core")
    all_files = list(ROOT.rglob("*.py"))
    total = len(all_files)
    console.print(f"📦 Found {total} Python scripts total.")
    to_archive = []
    to_keep = []
    for f in all_files:
        fname = f.name
        if is_temp_file(fname):
            to_archive.append(f)
        else:
            to_keep.append(f)
    console.print(f"🗂  Marked {len(to_archive)} for archival; keeping {len(to_keep)} core modules.")

    # Archive first
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    archive_path = ARCHIVE_DIR / f"deep_compact_{ts}"
    console.print(f"📦 Archiving redundant files to {archive_path}.tar.zst ...")
    zst_archive = archive_to_zst(archive_path, to_archive)
    footer("Complete.", "done")

    # Remove archived files
    removed = 0
    for f in to_archive:
        try:
            f.unlink()
            removed += 1
        except Exception:
            pass
    console.print(f"🧹 Removed {removed} redundant files.")

    # Remove empty directories
    removed_dirs = 0
    for d in sorted(ROOT.rglob("*"), reverse=True):
        if d.is_dir() and not any(d.iterdir()):
            d.rmdir()
            removed_dirs += 1
    console.print(f"🧭 Removed {removed_dirs} empty directories.")

    # Summary
    footer("Complete.", "done")

if __name__ == "__main__":
    main()

# === CLOUD SYNC HOOK ===
try:
    from subprocess import run
    uplink = Path("~/savant/services/scripts/cloud_engine/cloud_uplink.py").expanduser()
    archive_dir = Path("~/savant/archive").expanduser()
    if uplink.exists():
        console.print("☁️  Uploading archives to cloud...")
        run(["python3", str(uplink)], cwd=str(archive_dir))
except Exception as e:
    footer("Error.", "error")

# Auto-completion safeguard
pass
