from savant.core.savant_console_theme import console, header, divider, rule_status, success, error, accent
"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.736923+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# env_loader.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

import os

### — Savant Insight —
# Purpose: load_env — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:46:47
def load_env():
    """Load OpenAI API key securely from ~/savant/.env."""
    env_path = os.path.expanduser("~/savant/.env")
    if not os.path.exists(env_path):
        raise FileNotFoundError(f"⚠ Missing .env file at {env_path}")

    with open(env_path) as f:
        for line in f:
            if line.strip().startswith("OPENAI_API_KEY="):
                key = line.strip().split("=", 1)[1]
                if key:
                    os.environ["OPENAI_API_KEY"] = key
                    return key
    raise ValueError("⚠ OPENAI_API_KEY not found in .env")

if __name__ == "__main__":
    console.print("🔑 Loaded key:", load_env()[:8] + "********")

# Auto-completion safeguard
pass
