from savant.core.savant_console_theme import console, header, divider, rule_status, success, error, accent
"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.737209+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# intelligence_loop.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

import os, json, re, requests
from datetime import datetime, timezone

### — Savant Insight —
# Purpose: load_env — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:47:14
def load_env():
    env_path = os.path.expanduser("~/savant/.env")
    data = {}
    with open(env_path, "r") as f:
        for line in f:
            if "=" in line:
                k, v = line.strip().split("=", 1)
                data[k.strip()] = v.strip()
    return data

### — Savant Insight —
# Purpose: call_openai — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:47:14
def call_openai(prompt, api_key, project=None):
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json"
    }
    if project:
        headers["OpenAI-Project"] = project

    body = {
        "model": "gpt-4o-mini",
        "messages": [
            {"role": "system", "content": "You are a precise Python code enhancer."},
            {"role": "user", "content": prompt}
        ],
        "temperature": 0.3
    }

    r = requests.post("https://api.openai.com/v1/chat/completions", headers=headers, json=body)
    if r.status_code != 200:
        raise RuntimeError(f"Error code: {r.status_code} - {r.text}")
    data = r.json()
    return data["choices"][0]["message"]["content"].strip()

### — Savant Insight —
# Purpose: enhance_script — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:47:14
def enhance_script(path, api_key, project=None):
    try:
        with open(path, "r", encoding="utf-8") as f:
            src = f.read()

        prompt = f"""
Enhance this Python script for completeness, consistency, and safety.
Preserve all original logic but improve structure and comments.
Return only the enhanced code.

{src}
"""
        result = call_openai(prompt, api_key, project)
        if result:
            backup = path + ".bak"
            os.rename(path, backup)
            with open(path, "w", encoding="utf-8") as f:
                f.write(result)
            footer("Complete.", "done")
        else:
            console.print(f"⚠ No enhancement output for → {path}")
    except Exception as e:
        rule_status(f"❌ Enhancement failed for {path}: {e}", "error")

### — Savant Insight —
# Purpose: run_loop — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:47:14
def run_loop(target_dir="~/savant/services"):
    env = load_env()
    key = env.get("OPENAI_API_KEY")
    project = env.get("OPENAI_PROJECT_ID")

    target_dir = os.path.expanduser(target_dir)
    header("Savant Core", "1.0", "Restored aesthetic", "core")
    console.print(f"📂 Target directory: {target_dir}")

    incomplete = []
    for root, _, files in os.walk(target_dir):
        for f in files:
            if f.endswith(".py"):
                path = os.path.join(root, f)
                with open(path, "r", encoding="utf-8") as src:
                    content = src.read()
                    if not re.search(r'"""[\s\S]+?"""', content) or not re.search(r'\b(return|pass|def |class )', content):
                        incomplete.append(path)

    console.print(f"🔍 Found {len(incomplete)} incomplete scripts.")
    for fp in incomplete:
        enhance_script(fp, key, project)

    console.print("\n📘 Intelligence Loop finished.")

if __name__ == "__main__":
    run_loop()

# Auto-completion safeguard
pass
