from savant.core.savant_console_theme import console, header, divider, rule_status, success, error, accent
"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.739571+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# integration_cycle.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

```python
import os
import json
import pathlib
import subprocess
from datetime import datetime
from openai import OpenAI

# Define constants for base directory and log file path
BASE = pathlib.Path.home() / "savant"
LOG_PATH = BASE / "logs" / "integration_cycle.json"

# Initialize OpenAI client with the API key from environment variables
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

### — Savant Insight —
# Purpose: log — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:52:00
def log(event, data=None):
    """
    Log an event with optional data to a JSON file.

    Args:
        event (str): The event name to log.
        data (dict, optional): Additional data to log with the event.
    """
    # Ensure the log directory exists
    LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    
    # Create a log entry with the current timestamp
    entry = {
        "time": datetime.now().isoformat(),
        "event": event,
        "data": data or {}
    }
    
    # Append the log entry to the log file
    with open(LOG_PATH, "a") as f:
        f.write(json.dumps(entry) + "\n")

### — Savant Insight —
# Purpose: run_cycle — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:52:00
def run_cycle():
    """
    Execute the integration cycle for Savant AI, including OpenAI connection validation,
    knowledge synthesis, and syncing with cloud and GitHub.
    """
    header("Savant Core", "1.0", "Restored aesthetic", "core")
    log("integration_start")

    # 1️⃣ Validate OpenAI connection
    try:
        models = [m.id for m in client.models.list().data]
        footer("Complete.", "done")
        log("openai_models", {"count": len(models)})
    except Exception as e:
        rule_status(f"❌ OpenAI check failed: {e}", "error")
        log("openai_error", {"error": str(e)})
        return

    # 2️⃣ Knowledge synthesis
    console.print("📚 Generating domain synthesis...")
    synthesis_prompt = "Summarize Savant AI’s purpose and current architecture."
    try:
        resp = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": "You are Savant AI."},
                {"role": "user", "content": synthesis_prompt}
            ]
        )
        summary = resp.choices[0].message.content.strip()
        console.print(f"📘 Synthesis complete:\n{summary[:250]}...")
        log("synthesis_summary", {"summary": summary})
    except Exception as e:
        footer("Error.", "error")
        log("synthesis_error", {"error": str(e)})

    # 3️⃣ Cloud + GitHub sync
    console.print("☁️  Syncing cloud + GitHub...")
    try:
        subprocess.run(
            ["python3", str(BASE / "services/scripts/cloud_engine/cloud_uplink.py"), str(BASE / "archive")],
            check=True
        )
        subprocess.run(
            ["python3", str(BASE / "services/scripts/intelligence_cluster/export_cluster.py")],
            check=True
        )
    except subprocess.CalledProcessError as e:
        footer("Error.", "error")
        log("sync_error", {"error": str(e)})

    footer("Complete.", "done")
    log("integration_complete")

if __name__ == "__main__":
    run_cycle()
```

# Auto-completion safeguard
pass
