from savant.core.savant_console_theme import console, header, divider, rule_status, success, error, accent
"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.738341+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# knowledge_synthesis_cluster.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

"""
SAVANT KNOWLEDGE SYNTHESIS — v3.0
- Reads normalized texts from ~/savant/knowledge/raw_text/*.txt
- Splits into overlapping shards with domain tags
- Dedupes by content hash
- Writes shards to ~/savant/knowledge/shards/<domain>/<hash>.json
- Produces summary + level score aiming toward Level 6
"""
import os, json, pathlib
from datetime import datetime, timezone
from typing import Dict, List
from shard_tools import chunk_text, infer_domains, sha1_str, save_json, level_from_shards, log_event

BASE = pathlib.Path(os.path.expanduser("~/savant"))
KDIR = BASE / "knowledge"
RAW  = KDIR / "raw_text"
SHRD = KDIR / "shards"
META = KDIR / "meta"
LOGS = BASE / "logs"
for p in [KDIR, RAW, SHRD, META, LOGS]: p.mkdir(parents=True, exist_ok=True)

### — Savant Insight —
# Purpose: iso — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:49:40
def iso(): return datetime.now(timezone.utc).isoformat()

### — Savant Insight —
# Purpose: synth_one_text — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:49:40
def synth_one_text(fp: pathlib.Path, shards_added: List[str]):
    text = fp.read_text(encoding="utf-8", errors="ignore")
    text = text.strip()
    if not text: return 0
    doms = infer_domains(text)
    chunks = chunk_text(text, target_tokens=900, overlap_tokens=120)
    added = 0
    for ch in chunks:
        body = ch.strip()
        if not body: continue
        hid = sha1_str(body)
        domains = doms or ["general"]
        for d in domains:
            out = SHRD / d
            out.mkdir(parents=True, exist_ok=True)
            path = out / f"{hid}.json"
            if path.exists(): 
                continue
            doc = {
                "id": hid,
                "domain": d,
                "source": str(fp),
                "created": iso(),
                "tokens_est": len(body.split()),
                "body": body
            }
            save_json(path, doc)
            shards_added.append(str(path))
            added += 1
    return added

### — Savant Insight —
# Purpose: main — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:49:40
def main():
    files = sorted(RAW.glob("*.txt"))
    if not files:
        footer("Error.", "error")
        return
    console.print(f"🧪 Synthesizing from {len(files)} texts...")
    shards_added: List[str] = []
    total = 0
    for i, fp in enumerate(files, 1):
        added = synth_one_text(fp, shards_added)
        total += added
        if added:
            console.print(f"   • {fp.name}: +{added} shards")
    # Score level by total shards present
    current_count = sum(1 for _ in SHRD.rglob("*.json"))
    level = level_from_shards(current_count)
    summary = {
        "time": iso(),
        "texts": len(files),
        "added": total,
        "shard_total": current_count,
        "level": level
    }
    (META / "synthesis_summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")
    log_event("knowledge_synthesis_complete", summary)
    footer("Complete.", "done")

if __name__ == "__main__":
    main()

# Auto-completion safeguard
pass
