from savant.core.savant_console_theme import console, header, divider, rule_status, success, error, accent
"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.739286+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# migration_check_cluster.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

#!/data/data/com.termux/files/usr/bin/python3
"""
🧭 SAVANT MIGRATION READINESS CLUSTER v1.3
Adds full OpenAI project/org support for sk-proj keys.
"""

import os, sys, json, tempfile, requests, boto3
from datetime import datetime, timezone
from pathlib import Path

BASE = Path.home() / "savant"
LOG_PATH = BASE / "logs" / "migration_check.json"
ENV_PATH = BASE / ".env"

### — Savant Insight —
# Purpose: load_env — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:51:07
def load_env():
    if not ENV_PATH.exists():
        rule_status(f"❌ No .env found at {ENV_PATH}", "error")
        sys.exit(1)
    for line in open(ENV_PATH):
        if "=" in line and not line.strip().startswith("#"):
            k, v = line.strip().split("=", 1)
            os.environ[k] = v
    footer("Complete.", "done")

### — Savant Insight —
# Purpose: test_openai — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:51:07
def test_openai():
    console.print("\n🔑 Testing OpenAI API connection...")
    try:
        from openai import OpenAI
        key = os.getenv("OPENAI_API_KEY")
        org = os.getenv("OPENAI_ORG_ID")
        project = os.getenv("OPENAI_PROJECT_ID")
        if not key:
            raise ValueError("OPENAI_API_KEY missing in .env")

        client = OpenAI(
            api_key=key,
            organization=org if org else None,
            project=project if project else None
        )

        resp = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": "say 'ready'"}]
        )
        footer("Complete.", "done")
        return True

    except Exception as e:
        rule_status(f"❌ OpenAI test failed: {e}", "error")
        return False

### — Savant Insight —
# Purpose: test_github — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:51:07
def test_github():
    console.print("\n🐙 Testing GitHub token...")
    try:
        token = os.getenv("GITHUB_TOKEN")
        user = os.getenv("GITHUB_USER", "flypaper-creative")
        repo = os.getenv("GITHUB_REPO", "savant")
        r = requests.get("https://api.github.com/user",
                         headers={"Authorization": f"token {token}"})
        if r.status_code == 200:
            footer("Complete.", "done")
            return True
        footer("Error.", "error")
        return False
    except Exception as e:
        rule_status(f"❌ GitHub test failed: {e}", "error")
        return False

### — Savant Insight —
# Purpose: test_s3 — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:51:07
def test_s3():
    console.print("\n☁️  Testing S3 connectivity...")
    try:
        s3 = boto3.client(
            "s3",
            aws_access_key_id=os.getenv("AWS_ACCESS_KEY_ID"),
            aws_secret_access_key=os.getenv("AWS_SECRET_ACCESS_KEY"),
            region_name=os.getenv("AWS_DEFAULT_REGION", "us-east-1")
        )
        bucket = os.getenv("SAVANT_S3_BUCKET")
        tmp = Path(tempfile.gettempdir()) / "savant_test.txt"
        tmp.write_text("savant cloud test\n")
        key = f"diagnostics/{tmp.name}"
        s3.upload_file(str(tmp), bucket, key)
        footer("Complete.", "done")
        return True
    except Exception as e:
        rule_status(f"❌ S3 test failed: {e}", "error")
        return False

### — Savant Insight —
# Purpose: main — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:51:07
def main():
    header("Savant Core", "1.0", "Restored aesthetic", "core")
    load_env()
    oai = test_openai()
    gh = test_github()
    s3 = test_s3()
    all_ok = all([oai, gh, s3])
    footer("Complete.", "done")

if __name__ == "__main__":
    main()

# Auto-completion safeguard
pass
