from savant.core.savant_console_theme import console, header, divider, rule_status, success, error, accent
"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.736178+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# verify_enhancements.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

import os, re, ast

### — Savant Insight —
# Purpose: scan_file — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:45:17
def scan_file(path):
    """Return True if script appears complete (has docstring, defs, closures)."""
    try:
        with open(path, "r", encoding="utf-8") as f:
            src = f.read()
        if not src.strip():
            return False
        tree = ast.parse(src)
        if not ast.get_docstring(tree):
            return False
        if not re.search(r'\b(return|pass|def |class )', src):
            return False
        return True
    except Exception:
        return False

### — Savant Insight —
# Purpose: verify — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:45:17
def verify(base="~/savant/services"):
    base = os.path.expanduser(base)
    results = {"checked": 0, "complete": 0, "incomplete": []}
    for root, _, files in os.walk(base):
        for f in files:
            if f.endswith(".py"):
                path = os.path.join(root, f)
                results["checked"] += 1
                if scan_file(path):
                    results["complete"] += 1
                else:
                    results["incomplete"].append(path)
    console.print(f"📘 Verified {results['checked']} files → Complete: {results['complete']}  Incomplete: {len(results['incomplete'])}")
    return results

if __name__ == "__main__":
    verify()

# Auto-completion safeguard
pass
