"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.296696+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# memory_engine.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

#!/usr/bin/env python3
"""
SAVANT CONTINUITY ENGINE (Phase 13)
Stores conversation embeddings for cross-session context memory.
"""
from openai import OpenAI
from pathlib import Path
import orjson as json, numpy as np, os
from pydantic_settings import BaseSettings

ROOT=Path.home()/ "savant"/"memory"
ROOT.mkdir(parents=True,exist_ok=True)
load_dotenv(Path.home() / "savant" / ".env")/".env")
client=OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

### — Savant Insight —
# Purpose: embed — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:35:22
def embed(text:str):
    e=client.embeddings.create(model="text-embedding-3-small",input=text)
    return np.array(e.data[0].embedding)

### — Savant Insight —
# Purpose: store — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:35:22
def store(ref,text):
    vec=embed(text).tolist()
    data={"ref":ref,"text":text,"embedding":vec}
    (ROOT/f"{ref}.json").write_text(json.dumps(data))

### — Savant Insight —
# Purpose: recall — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:35:22
def recall(query):
    q=embed(query)
    best=None;score=-1
    for f in ROOT.glob("*.json"):
        d=json.loads(f.read_text())
        v=np.array(d["embedding"])
        sim=float(np.dot(q,v)/(np.linalg.norm(q)*np.linalg.norm(v)))
        if sim>score:score,best=sim,d
    return best["text"] if best else "No related context."


# Auto-completion safeguard
pass