"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.767415+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# main.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

"""
Enhanced by Savant Clean+Complete Cluster v1.0 — 2025-10-30T06:11:07.933705+00:00
"""
from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse
import openai, os

app=FastAPI(title="Savant API Gateway", version="3.5")
openai.api_key=os.getenv("OPENAI_API_KEY")

@app.get("/health")
async def health():
    return {"status":"ok","version":"3.5","ai_key":bool(openai.api_key)}

@app.post("/api/ai")
async def ai_chat(request:Request):
    data=await request.json()
    prompt=data.get("prompt","")
    if not openai.api_key: return JSONResponse({"error":"Missing API key"},status_code=401)
    try:
        res=openai.chat.completions.create(model="gpt-4o-mini",messages=[{"role":"user","content":prompt}])
        return {"response":res.choices[0].message.content}
    except Exception as e:
        return JSONResponse({"error":str(e)},status_code=500)


# Auto-completion safeguard
pass