"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.294469+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# visualizer.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

#!/usr/bin/env python3
"""
SAVANT FRACTAL VISUALIZATION ENGINE (Phase 6.0)
Interactive 3D visualizer for fractal_core hierarchy using Plotly 3D.
Outputs both HTML and JSON views for integration with wb_ui dashboard.
"""

import orjson as json, math
from pathlib import Path
import plotly.graph_objects as go
from datetime import datetime, timezone

ROOT = Path.home()/ "savant"
DATA = ROOT/"services"/"scripts"/"fractal_core"/"fractal_graph.json"
OUT  = ROOT/"services"/"scripts"/"fractal_visualization"/"fractal_scene.html"

### — Savant Insight —
# Purpose: utc — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:33:33
def utc(): return datetime.now(timezone.utc).isoformat()

### — Savant Insight —
# Purpose: flatten — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:33:33
def flatten(node, depth=0, parent=None):
    nodes=[]
    nodes.append({"id":node["id"],"name":node["name"],"curv":node["curvature"],"depth":depth,"parent":parent})
    for c in node.get("children",[]): nodes+=flatten(c,depth+1,node["id"])
    return nodes

### — Savant Insight —
# Purpose: visualize — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:33:33
def visualize():
    data=json.loads(DATA.read_text())
    nodes=flatten(data)
    xs=[math.cos(n["depth"])*n["curv"]*2 for n in nodes]
    ys=[math.sin(n["depth"])*n["curv"]*2 for n in nodes]
    zs=[n["depth"]*1.2 for n in nodes]
    text=[n["name"] for n in nodes]

    fig=go.Figure(data=[go.Scatter3d(
        x=xs,y=ys,z=zs,mode="markers+text",text=text,textposition="top center",
        marker=dict(size=8,color=[n["curv"] for n in nodes],
                    colorscale="YlOrBr",opacity=0.9)
    )])
    fig.update_layout(scene=dict(bgcolor="#0e0e10"),
                      paper_bgcolor="#0e0e10",
                      font=dict(color="#e4c66f"),
                      title="Savant Fractal Hierarchy")
    OUT.write_text(fig.to_html(full_html=True,include_plotlyjs="cdn"))
    footer("Complete.", "done")

if __name__=="__main__":
    visualize()


# Auto-completion safeguard
pass