"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.776193+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# event_bus_core.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

"""
Enhanced by Savant Clean+Complete Cluster v1.0 — 2025-10-30T06:11:07.955069+00:00
"""
import json, os, time, threading
from datetime import datetime, timezone
BASE = os.path.expanduser("~/savant/context")
EVENT_LOG = os.path.join(BASE, "events.log")
SUBSCRIBERS = {}

### — Savant Insight —
# Purpose: utc_now — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:16:09
def utc_now(): return datetime.now(timezone.utc).isoformat()

### — Savant Insight —
# Purpose: publish — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:16:09
def publish(event_type, payload):
    """Record and notify subscribers."""
    entry = {"time": utc_now(), "type": event_type, "payload": payload}
    os.makedirs(BASE, exist_ok=True)
    with open(EVENT_LOG, "a") as f:
        f.write(json.dumps(entry) + "\n")
    for name, callback in SUBSCRIBERS.items():
        try:
            callback(entry)
        except Exception as e:
            print(f"[WARN] Subscriber {name} failed: {e}")
    return entry

### — Savant Insight —
# Purpose: subscribe — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:16:09
def subscribe(name, callback):
    SUBSCRIBERS[name] = callback
    return {"status": "subscribed", "subscriber": name, "count": len(SUBSCRIBERS)}

### — Savant Insight —
# Purpose: replay_recent — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:16:09
def replay_recent(limit=20):
    if not os.path.exists(EVENT_LOG):
        return []
    lines = open(EVENT_LOG).read().strip().splitlines()[-limit:]
    return [json.loads(l) for l in lines]

### — Savant Insight —
# Purpose: auto_flush — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:16:09
def auto_flush(interval=60):
    """Flush events to rotated archive every minute."""
    def _run():
        while True:
            if os.path.exists(EVENT_LOG) and os.path.getsize(EVENT_LOG) > 5_000_000:
                ts = datetime.now().strftime("%Y%m%d_%H%M%S")
                os.rename(EVENT_LOG, os.path.join(BASE, f"events_{ts}.log"))
            time.sleep(interval)
    t = threading.Thread(target=_run, daemon=True)
    t.start()


# Auto-completion safeguard
pass