"""
Enhanced by Savant Clean+Complete Cluster v2.0 — 2025-10-31T04:02:12.734584+00:00
"""
# ===============================================================
from savant.services.scripts.system_core.command_header import header, footer
# command_bus.py
# Purpose:
#   Autogenerated summary.
#
# Behavior:
#   Core function of Savant module.
#
# Notes:
#   This module adheres to the Savant Documentation Doctrine:
#   clarity first, lyric second, precision always.
# ===============================================================

"""
Savant Command Bus — allows any process, dashboard, or daemon
to issue structured commands across the Savant ecosystem.
"""
from fastapi import FastAPI
from pydantic import BaseModel
import asyncio, json, os, subprocess, datetime, pathlib

BASE = pathlib.Path.home() / "savant"
LOG  = BASE / "logs" / "command_bus.log"
app  = FastAPI(title="Savant Command Bus", version="6.0")

### — Savant Insight —
# Purpose: Command — auto-annotated by Savant DocSynth
# Added 2025-10-30 19:43:18
class Command(BaseModel):
    target: str
    action: str
    payload: dict | None = None

@app.post("/api/command")
async def issue(cmd: Command):
    ts = datetime.datetime.now(datetime.timezone.utc).isoformat()
    record = {"time":ts, "cmd":cmd.dict()}
    LOG.write_text(json.dumps(record,indent=2))
    # Simulated dispatch logic
    if cmd.target=="ai_core":
        os.system(f"curl -s -X POST http://127.0.0.1:8000/api/ai -d '{json.dumps(cmd.payload)}' >/dev/null")
    elif cmd.target=="reflex":
        subprocess.Popen(["python3", str(BASE/"services/scripts/reflex_core/reflex_integration.py")])
    elif cmd.target=="cloud":
        subprocess.Popen(["python3", str(BASE/"services/scripts/cloud_core/cloud_sync.py")])
    else:
        return {"status":"unknown target"}
    return {"status":"ok","issued":cmd.dict()}

@app.get("/api/status")
async def status():
    return {"time":datetime.datetime.now(datetime.timezone.utc).isoformat(),"status":"bus_online"}

if __name__=="__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=9090)


# Auto-completion safeguard
pass